export const rawCareers = [
  {
    id: 'android-developer',
    subDomainId: 'android',
    domainId: 'app-development',
    title: 'Android Developer',
    emoji: '🤖',
    tagline: 'Craft Android apps used by billions',
    description: 'Build native Android applications that run on billions of devices worldwide. You\'ll master Kotlin, Jetpack Compose, and the Android ecosystem to create performant, beautiful mobile experiences.',
    salary: { entry: '$75,000', mid: '$105,000', senior: '$145,000' },
    growthRate: '+22%',
    demandLevel: 'high',
    workStyle: 'remote-first',
    timeToReady: '8-12 months',
    keySkills: ['Kotlin', 'Jetpack Compose', 'Android SDK', 'MVVM', 'Coroutines', 'Room DB'],
    dayInLife: [
      'Morning standup with the mobile team',
      'Build new features in Kotlin with Jetpack Compose',
      'Review pull requests and provide feedback',
      'Optimize app performance and reduce memory usage',
      'Test on different Android versions and screen sizes',
    ],
    pros: ['Large device ecosystem', 'Strong open-source community', 'Good remote opportunities', 'Kotlin is modern and fun'],
    cons: ['Android fragmentation across devices', 'Google Play policies', 'Legacy code in older apps'],
    companies: ['Google', 'Samsung', 'Spotify', 'Uber', 'Airbnb', 'Flipkart'],
    requiredSkillIds: ['kotlin', 'jetpack-compose', 'android-sdk', 'git'],
    roadmapId: 'android-developer-roadmap',
    defaultMatchScore: 91,
  },
  {
    id: 'ios-developer',
    subDomainId: 'ios',
    domainId: 'app-development',
    title: 'iOS Developer',
    emoji: '🍎',
    tagline: 'Build apps for the world\'s most premium platform',
    description: 'Create stunning iOS applications using Swift and SwiftUI. iOS developers craft experiences for iPhones and iPads, benefiting from Apple\'s premium ecosystem and a highly engaged user base.',
    salary: { entry: '$80,000', mid: '$115,000', senior: '$155,000' },
    growthRate: '+18%',
    demandLevel: 'high',
    workStyle: 'remote-first',
    timeToReady: '9-14 months',
    keySkills: ['Swift', 'SwiftUI', 'UIKit', 'Core Data', 'Combine', 'Xcode'],
    dayInLife: [
      'Design UI layouts with SwiftUI',
      'Implement feature requirements from product',
      'Debug and fix reported crashes from TestFlight',
      'Collaborate with designers on animations',
      'Prepare app submission for App Store review',
    ],
    pros: ['Premium platform', 'High-quality user base', 'Great tooling with Xcode', 'Apple ecosystem integration'],
    cons: ['App Store approval process', 'Mac required for development', 'Smaller device variety'],
    companies: ['Apple', 'Instagram', 'Duolingo', 'Robinhood', 'LinkedIn'],
    requiredSkillIds: ['swift', 'swiftui', 'xcode', 'git'],
    roadmapId: 'ios-developer-roadmap',
    defaultMatchScore: 78,
  },
  {
    id: 'flutter-developer',
    subDomainId: 'flutter',
    domainId: 'app-development',
    title: 'Flutter Developer',
    emoji: '🎯',
    tagline: 'One codebase. Every platform.',
    description: 'Build cross-platform applications for iOS, Android, web, and desktop from a single Dart codebase using Flutter. Flutter developers are highly sought after for their efficiency and versatility.',
    salary: { entry: '$70,000', mid: '$98,000', senior: '$135,000' },
    growthRate: '+28%',
    demandLevel: 'explosive',
    workStyle: 'remote-first',
    timeToReady: '6-10 months',
    keySkills: ['Dart', 'Flutter', 'BLoC', 'Provider', 'Riverpod', 'Firebase'],
    dayInLife: [
      'Build shared UI components with Flutter widgets',
      'Implement state management with BLoC pattern',
      'Test on iOS simulator and Android emulator simultaneously',
      'Integrate Firebase for backend services',
      'Deploy to both App Store and Play Store',
    ],
    pros: ['Single codebase for all platforms', 'Fast development cycle', 'Growing demand', 'Great UI performance'],
    cons: ['Larger app size', 'Dart is less common', 'Some platform-specific features need native code'],
    companies: ['BMW', 'eBay', 'Alibaba', 'Dream11', 'PhonePe'],
    requiredSkillIds: ['dart', 'flutter', 'git', 'firebase-basics'],
    roadmapId: 'flutter-developer-roadmap',
    defaultMatchScore: 85,
  },
  {
    id: 'react-native-developer',
    subDomainId: 'react-native',
    domainId: 'app-development',
    title: 'React Native Developer',
    emoji: '⚛️',
    tagline: 'JavaScript power meets native performance',
    description: 'Build native mobile apps using JavaScript and React. React Native developers leverage web skills to create truly native mobile experiences, making it ideal for teams with existing web expertise.',
    salary: { entry: '$72,000', mid: '$100,000', senior: '$138,000' },
    growthRate: '+20%',
    demandLevel: 'high',
    workStyle: 'hybrid',
    timeToReady: '5-9 months',
    keySkills: ['JavaScript', 'TypeScript', 'React', 'React Native', 'Redux', 'Expo'],
    dayInLife: [
      'Write shared components usable across iOS and Android',
      'Debug platform-specific rendering issues',
      'Optimize JavaScript bundle size and startup time',
      'Integrate third-party native modules',
      'Deploy OTA updates with Expo',
    ],
    pros: ['Uses JavaScript/TypeScript', 'Share code with React web', 'Hot reloading', 'Large community'],
    cons: ['Performance ceiling vs native', 'Native module bridging complexity', 'Version upgrade challenges'],
    companies: ['Facebook', 'Microsoft', 'Shopify', 'Discord', 'Walmart'],
    requiredSkillIds: ['javascript', 'typescript', 'react', 'react-native', 'git'],
    roadmapId: 'react-native-developer-roadmap',
    defaultMatchScore: 72,
  },
  {
    id: 'ml-engineer',
    subDomainId: 'ml-engineering',
    domainId: 'ai-ml',
    title: 'ML Engineer',
    emoji: '🤖',
    tagline: 'Train models that change everything',
    description: 'Design, train, and deploy machine learning models at scale. ML Engineers bridge the gap between research and production, building the systems that power AI products used by millions.',
    salary: { entry: '$100,000', mid: '$140,000', senior: '$190,000' },
    growthRate: '+38%',
    demandLevel: 'explosive',
    workStyle: 'remote-first',
    timeToReady: '12-18 months',
    keySkills: ['Python', 'TensorFlow', 'PyTorch', 'MLflow', 'Kubernetes', 'SQL'],
    dayInLife: [
      'Analyze model performance metrics and identify bottlenecks',
      'Design feature engineering pipelines',
      'Train and tune deep learning models',
      'Deploy models to production with monitoring',
      'Collaborate with product on AI feature requirements',
    ],
    pros: ['Highest paying tech role', 'Cutting-edge work', 'Strong remote culture', 'Explosive demand'],
    cons: ['Long learning curve', 'Compute costs', 'Research keeps moving fast'],
    companies: ['Google', 'OpenAI', 'Anthropic', 'Meta AI', 'NVIDIA', 'Amazon'],
    requiredSkillIds: ['python', 'tensorflow', 'pytorch', 'statistics', 'linear-algebra'],
    roadmapId: 'ml-engineer-roadmap',
    defaultMatchScore: 88,
  },
  {
    id: 'data-scientist',
    subDomainId: 'data-science',
    domainId: 'ai-ml',
    title: 'Data Scientist',
    emoji: '📊',
    tagline: 'Turn data into decisions',
    description: 'Extract meaningful insights from complex datasets to drive business decisions. Data Scientists combine statistics, programming, and domain expertise to solve the problems companies care most about.',
    salary: { entry: '$90,000', mid: '$125,000', senior: '$165,000' },
    growthRate: '+28%',
    demandLevel: 'high',
    workStyle: 'hybrid',
    timeToReady: '10-15 months',
    keySkills: ['Python', 'R', 'SQL', 'Pandas', 'Scikit-learn', 'Tableau'],
    dayInLife: [
      'Explore and clean datasets from various sources',
      'Build predictive models for business outcomes',
      'Create data visualizations for stakeholders',
      'Present findings to leadership',
      'Design A/B tests and analyze results',
    ],
    pros: ['Business impact is visible', 'Diverse industries', 'Creative problem solving', 'Good compensation'],
    cons: ['Data quality issues are common', 'Models often not deployed', 'Requires strong communication'],
    companies: ['Netflix', 'Airbnb', 'LinkedIn', 'Twitter', 'Stripe', 'Zalando'],
    requiredSkillIds: ['python', 'statistics', 'sql', 'pandas', 'visualization'],
    roadmapId: 'data-scientist-roadmap',
    defaultMatchScore: 76,
  },
  {
    id: 'frontend-developer',
    subDomainId: 'frontend',
    domainId: 'web-development',
    title: 'Frontend Developer',
    emoji: '🎨',
    tagline: 'Craft the faces of the web',
    description: 'Build the visual and interactive layer of web applications. Frontend developers create the experiences users see and touch, combining HTML, CSS, and JavaScript to craft beautiful, performant interfaces.',
    salary: { entry: '$65,000', mid: '$95,000', senior: '$130,000' },
    growthRate: '+15%',
    demandLevel: 'high',
    workStyle: 'remote-first',
    timeToReady: '6-10 months',
    keySkills: ['HTML/CSS', 'JavaScript', 'TypeScript', 'React', 'Next.js', 'Tailwind CSS'],
    dayInLife: [
      'Convert Figma designs to pixel-perfect React components',
      'Optimize Lighthouse scores and Core Web Vitals',
      'Build accessible and responsive UI',
      'Review design handoff and flag inconsistencies',
      'Collaborate with backend on API integration',
    ],
    pros: ['Immediate visual feedback', 'Creative expression', 'Strong demand', 'Excellent remote opportunities'],
    cons: ['Browser compatibility headaches', 'JavaScript fatigue', 'Design debates'],
    companies: ['Vercel', 'Figma', 'Atlassian', 'Notion', 'Linear', 'Webflow'],
    requiredSkillIds: ['html-css', 'javascript', 'typescript', 'react', 'git'],
    roadmapId: 'frontend-developer-roadmap',
    defaultMatchScore: 82,
  },
  {
    id: 'fullstack-developer',
    subDomainId: 'fullstack',
    domainId: 'web-development',
    title: 'Full Stack Developer',
    emoji: '🔗',
    tagline: 'Build everything, end to end',
    description: 'Develop both frontend and backend systems, owning the complete product stack. Full Stack Developers are the Swiss Army knives of tech — versatile, valuable, and able to ship complete features independently.',
    salary: { entry: '$75,000', mid: '$108,000', senior: '$148,000' },
    growthRate: '+19%',
    demandLevel: 'high',
    workStyle: 'remote-first',
    timeToReady: '10-14 months',
    keySkills: ['React', 'Node.js', 'TypeScript', 'PostgreSQL', 'Docker', 'AWS'],
    dayInLife: [
      'Design and implement REST/GraphQL APIs',
      'Build React components consuming your own APIs',
      'Set up CI/CD pipelines for deployment',
      'Debug production issues across the stack',
      'Lead technical architecture discussions',
    ],
    pros: ['Maximum flexibility', 'Can ship features solo', 'High demand at startups', 'Breadth of knowledge'],
    cons: ['Hard to be expert at everything', 'Context switching', 'More to keep up with'],
    companies: ['Stripe', 'GitHub', 'Shopify', 'Cloudflare', 'Vercel', 'Supabase'],
    requiredSkillIds: ['html-css', 'javascript', 'react', 'nodejs', 'sql', 'git', 'docker'],
    roadmapId: 'fullstack-developer-roadmap',
    defaultMatchScore: 80,
  },
  {
    id: 'product-designer',
    subDomainId: 'product-design',
    domainId: 'ui-ux',
    title: 'Product Designer',
    emoji: '📐',
    tagline: 'Design products people fall in love with',
    description: 'Own the end-to-end design of digital products, from research and wireframes to high-fidelity prototypes. Product Designers shape how millions of people interact with technology every day.',
    salary: { entry: '$70,000', mid: '$100,000', senior: '$140,000' },
    growthRate: '+18%',
    demandLevel: 'high',
    workStyle: 'hybrid',
    timeToReady: '8-12 months',
    keySkills: ['Figma', 'User Research', 'Prototyping', 'Design Systems', 'Usability Testing', 'Framer'],
    dayInLife: [
      'User interviews to understand pain points',
      'Create wireframes and user flows',
      'Design high-fidelity mockups in Figma',
      'Present design proposals to stakeholders',
      'Collaborate with engineers on implementation',
    ],
    pros: ['High creative impact', 'See your work used by real people', 'Collaborative environment', 'Growing demand'],
    cons: ['Subjectivity in feedback', 'Design by committee', 'Design tools keep changing'],
    companies: ['Apple', 'Google', 'Figma', 'Notion', 'Spotify', 'Airbnb'],
    requiredSkillIds: ['figma', 'ux-research', 'prototyping', 'design-systems'],
    roadmapId: 'product-designer-roadmap',
    defaultMatchScore: 69,
  },
  {
    id: 'unity-developer',
    subDomainId: 'unity',
    domainId: 'game-development',
    title: 'Unity Developer',
    emoji: '🎲',
    tagline: 'Build worlds millions will explore',
    description: 'Create 2D and 3D games using the Unity Engine with C#. Unity developers work across mobile, PC, console, and VR platforms, making Unity one of the most versatile game engines in the industry.',
    salary: { entry: '$65,000', mid: '$92,000', senior: '$125,000' },
    growthRate: '+12%',
    demandLevel: 'moderate',
    workStyle: 'hybrid',
    timeToReady: '10-15 months',
    keySkills: ['C#', 'Unity', 'Game Physics', 'Shader Graph', 'Unity Netcode', 'AR Foundation'],
    dayInLife: [
      'Implement game mechanics in C#',
      'Optimize draw calls and frame rate',
      'Collaborate with artists on asset integration',
      'Test gameplay on target platforms',
      'Implement multiplayer features with Netcode',
    ],
    pros: ['Creative and fun work', 'Massive community', 'Multi-platform', 'Growing VR/AR demand'],
    cons: ['Gaming industry crunch culture', 'Lower pay vs enterprise software', 'Unity licensing changes'],
    companies: ['EA', 'Niantic', 'Supercell', 'King', 'Scopely', 'Jam City'],
    requiredSkillIds: ['csharp', 'unity', 'game-math', 'git'],
    roadmapId: 'unity-developer-roadmap',
    defaultMatchScore: 74,
  },
  {
    id: 'ethical-hacker',
    subDomainId: 'ethical-hacking',
    domainId: 'cyber-security',
    title: 'Ethical Hacker',
    emoji: '💀',
    tagline: 'Think like an attacker. Protect like a defender.',
    description: 'Perform authorized penetration testing to find vulnerabilities before malicious hackers do. Ethical Hackers are the cybersecurity frontline, using attacker mindsets to protect organizations.',
    salary: { entry: '$80,000', mid: '$115,000', senior: '$160,000' },
    growthRate: '+31%',
    demandLevel: 'explosive',
    workStyle: 'remote-first',
    timeToReady: '12-18 months',
    keySkills: ['Kali Linux', 'Metasploit', 'Burp Suite', 'Python', 'Networking', 'OSCP'],
    dayInLife: [
      'Scope and plan penetration testing engagements',
      'Perform reconnaissance on target systems',
      'Execute controlled attack simulations',
      'Document findings and vulnerabilities',
      'Present remediation recommendations to clients',
    ],
    pros: ['Highly specialized and valued', 'Exciting and challenging', 'Strong demand', 'Good remote options'],
    cons: ['Legal and ethical constraints', 'Constant skill updates required', 'Certifications can be expensive'],
    companies: ['CrowdStrike', 'Palo Alto Networks', 'Rapid7', 'IBM Security', 'Deloitte'],
    requiredSkillIds: ['networking', 'linux', 'python', 'web-security', 'oscp'],
    roadmapId: 'ethical-hacker-roadmap',
    defaultMatchScore: 65,
  },
];
