export interface RawCareer {
  id: string;
  subDomainId: string;
  domainId: string;
  title: string;
  emoji: string;
  tagline: string;
  description: string;
  matchScore?: number;
  salary: {
    entry: string;
    mid: string;
    senior: string;
  };
  growthRate: string;
  demandLevel: 'explosive' | 'high' | 'moderate' | 'stable';
  workStyle: 'remote-first' | 'hybrid' | 'onsite';
  timeToReady: string;
  keySkills: string[];
  dayInLife: string[];
  pros: string[];
  cons: string[];
  companies: string[];
  requiredSkillIds: string[];
  roadmapId: string;
}

export const rawCareers: RawCareer[] = [
  // 1. Android Developer
  {
    id: 'android-developer',
    subDomainId: 'android',
    domainId: 'app-development',
    title: 'Android Developer',
    emoji: '🤖',
    tagline: 'Craft Android apps used by billions',
    description: 'Build native Android applications using Kotlin, Jetpack Compose, Coroutines, and Room DB for global smartphone users.',
    salary: { entry: '$75,000', mid: '$105,000', senior: '$145,000' },
    growthRate: '+22%',
    demandLevel: 'high',
    workStyle: 'remote-first',
    timeToReady: '8-12 months',
    keySkills: ['Kotlin', 'Jetpack Compose', 'Android SDK', 'MVVM', 'Coroutines', 'Room DB'],
    dayInLife: [
      'Morning standup with mobile engineers',
      'Build UI layouts with Jetpack Compose',
      'Integrate REST APIs and Room local cache',
      'Optimize app performance and reduce memory usage',
      'Test across diverse screen sizes',
    ],
    pros: ['Large device ecosystem', 'Strong open-source community', 'Great remote opportunities'],
    cons: ['Device fragmentation', 'Google Play review policies'],
    companies: ['Google', 'Samsung', 'Spotify', 'Uber', 'Airbnb'],
    requiredSkillIds: ['kotlin', 'jetpack-compose', 'android-sdk', 'git'],
    roadmapId: 'android-developer-roadmap',
  },

  // 2. iOS Developer
  {
    id: 'ios-developer',
    subDomainId: 'ios',
    domainId: 'app-development',
    title: 'iOS Developer',
    emoji: '🍎',
    tagline: 'Build apps for Apple premium ecosystem',
    description: 'Create fluid iOS experiences using Swift, SwiftUI, SwiftData, Combine, and Apple HIG design principles.',
    salary: { entry: '$80,000', mid: '$115,000', senior: '$155,000' },
    growthRate: '+18%',
    demandLevel: 'high',
    workStyle: 'remote-first',
    timeToReady: '9-14 months',
    keySkills: ['Swift', 'SwiftUI', 'UIKit', 'SwiftData', 'Combine', 'Xcode'],
    dayInLife: [
      'Design declarative screens in SwiftUI',
      'Implement async networking and SwiftData persistence',
      'Debug memory leaks using Instruments',
      'Prepare TestFlight builds for QA',
      'Publish to the App Store',
    ],
    pros: ['Premium user base', 'Unified hardware and software', 'Excellent tooling in Xcode'],
    cons: ['Mac required for development', 'App Store approval guidelines'],
    companies: ['Apple', 'Instagram', 'Robinhood', 'Duolingo', 'LinkedIn'],
    requiredSkillIds: ['swift', 'swiftui', 'xcode', 'git'],
    roadmapId: 'ios-developer-roadmap',
  },

  // 3. Flutter Developer
  {
    id: 'flutter-developer',
    subDomainId: 'flutter',
    domainId: 'app-development',
    title: 'Flutter Developer',
    emoji: '🎯',
    tagline: 'One codebase. Every platform.',
    description: 'Build native multi-platform applications for iOS, Android, web, and desktop using Dart and Flutter widgets.',
    salary: { entry: '$70,000', mid: '$98,000', senior: '$135,000' },
    growthRate: '+28%',
    demandLevel: 'explosive',
    workStyle: 'remote-first',
    timeToReady: '6-10 months',
    keySkills: ['Dart', 'Flutter', 'BLoC', 'Riverpod', 'Firebase', 'REST APIs'],
    dayInLife: [
      'Build shared UI components with Flutter widgets',
      'Manage reactive state with Riverpod or BLoC',
      'Test concurrently on iOS and Android simulators',
      'Integrate Firebase cloud functions',
      'Deploy multi-platform releases',
    ],
    pros: ['Single codebase', 'Fast hot-reload iteration', 'High demand at startups'],
    cons: ['Larger initial bundle size', 'Platform channels required for custom native APIs'],
    companies: ['BMW', 'eBay', 'Alibaba', 'Dream11', 'PhonePe'],
    requiredSkillIds: ['dart', 'flutter', 'git', 'firebase-basics'],
    roadmapId: 'flutter-developer-roadmap',
  },

  // 4. React Native Developer
  {
    id: 'react-native-developer',
    subDomainId: 'react-native',
    domainId: 'app-development',
    title: 'React Native Developer',
    emoji: '⚛️',
    tagline: 'JavaScript power meets native mobile performance',
    description: 'Leverage JavaScript, TypeScript, and React to build performant iOS and Android mobile apps with Expo and Reanimated.',
    salary: { entry: '$72,000', mid: '$100,000', senior: '$138,000' },
    growthRate: '+20%',
    demandLevel: 'high',
    workStyle: 'hybrid',
    timeToReady: '5-9 months',
    keySkills: ['JavaScript', 'TypeScript', 'React Native', 'Expo', 'Reanimated', 'Redux'],
    dayInLife: [
      'Develop shared React Native screens and hooks',
      'Implement 60fps gesture animations with Reanimated 3',
      'Optimize Hermes bundle performance',
      'Push over-the-air updates with EAS Update',
      'Collaborate with web team on shared libraries',
    ],
    pros: ['Code sharing with web React', 'Massive npm ecosystem', 'Fast iteration with Expo'],
    cons: ['Native bridge debugging', 'Upgrade complexity across major versions'],
    companies: ['Meta', 'Microsoft', 'Shopify', 'Discord', 'Coinbase'],
    requiredSkillIds: ['javascript', 'typescript', 'react', 'react-native', 'git'],
    roadmapId: 'react-native-developer-roadmap',
  },

  // 5. ML Engineer
  {
    id: 'ml-engineer',
    subDomainId: 'ml-engineering',
    domainId: 'machine-learning',
    title: 'ML Engineer',
    emoji: '⚙️',
    tagline: 'Train and deploy deep learning models at scale',
    description: 'Design, train, and deploy production machine learning pipelines, PyTorch neural networks, and scalable inference APIs.',
    salary: { entry: '$100,000', mid: '$140,000', senior: '$190,000' },
    growthRate: '+38%',
    demandLevel: 'explosive',
    workStyle: 'remote-first',
    timeToReady: '12-18 months',
    keySkills: ['Python', 'PyTorch', 'TensorFlow', 'MLflow', 'Docker', 'Kubernetes'],
    dayInLife: [
      'Design feature engineering pipelines in Python',
      'Train deep neural networks on GPU clusters',
      'Optimize inference latency with ONNX and TensorRT',
      'Containerize inference servers with FastAPI and Docker',
      'Monitor model drift and performance metrics in production',
    ],
    pros: ['High compensation', 'Frontier technical work', 'Huge enterprise demand'],
    cons: ['Steep math learning curve', 'High compute and GPU infrastructure costs'],
    companies: ['Google', 'OpenAI', 'Anthropic', 'Meta AI', 'NVIDIA'],
    requiredSkillIds: ['python', 'tensorflow', 'pytorch', 'statistics', 'linear-algebra'],
    roadmapId: 'ml-engineer-roadmap',
  },

  // 6. Data Scientist
  {
    id: 'data-scientist',
    subDomainId: 'data-science-core',
    domainId: 'data-science',
    title: 'Data Scientist',
    emoji: '📊',
    tagline: 'Transform raw data into business intelligence',
    description: 'Extract statistical insights, build predictive models, design A/B experiments, and guide executive decision-making.',
    salary: { entry: '$90,000', mid: '$125,000', senior: '$165,000' },
    growthRate: '+28%',
    demandLevel: 'high',
    workStyle: 'hybrid',
    timeToReady: '10-15 months',
    keySkills: ['Python', 'SQL', 'Pandas', 'Scikit-learn', 'Statistics', 'Tableau'],
    dayInLife: [
      'Query and aggregate data from Snowflake/BigQuery',
      'Perform exploratory data analysis in Jupyter notebooks',
      'Build predictive classification and regression models',
      'Design statistical A/B test experiments',
      'Present analytical findings to stakeholders',
    ],
    pros: ['Direct business impact', 'Diverse application domains', 'Great compensation'],
    cons: ['Data cleaning is time-consuming', 'Requires strong communication skills'],
    companies: ['Netflix', 'Airbnb', 'Stripe', 'Uber', 'Spotify'],
    requiredSkillIds: ['python', 'statistics', 'sql', 'pandas', 'visualization'],
    roadmapId: 'data-scientist-roadmap',
  },

  // 7. Frontend Developer
  {
    id: 'frontend-developer',
    subDomainId: 'frontend-react',
    domainId: 'frontend-development',
    title: 'Frontend Developer',
    emoji: '🎨',
    tagline: 'Craft modern, responsive web interfaces',
    description: 'Build fast, accessible, and interactive user experiences using React, Next.js, TypeScript, and modern CSS frameworks.',
    salary: { entry: '$65,000', mid: '$95,000', senior: '$130,000' },
    growthRate: '+15%',
    demandLevel: 'high',
    workStyle: 'remote-first',
    timeToReady: '6-10 months',
    keySkills: ['HTML/CSS', 'JavaScript', 'TypeScript', 'React', 'Next.js', 'Tailwind CSS'],
    dayInLife: [
      'Implement Figma mockups in React with Tailwind',
      'Optimize Core Web Vitals (LCP, INP, CLS)',
      'Connect client components to backend REST/GraphQL APIs',
      'Write unit tests with Vitest and Testing Library',
      'Deploy preview branches to Vercel',
    ],
    pros: ['Immediate visual feedback', 'High remote job availability', 'Vibrant community'],
    cons: ['Fast ecosystem changes', 'Browser cross-compatibility quirks'],
    companies: ['Vercel', 'Figma', 'Linear', 'Notion', 'Atlassian'],
    requiredSkillIds: ['html-css', 'javascript', 'typescript', 'react', 'git'],
    roadmapId: 'frontend-developer-roadmap',
  },

  // 8. Full Stack Developer
  {
    id: 'fullstack-developer',
    subDomainId: 'fullstack-mern',
    domainId: 'fullstack-development',
    title: 'Full Stack Developer',
    emoji: '🔗',
    tagline: 'Build everything from database to browser',
    description: 'Own end-to-end features across frontend, backend, databases, authentication, and cloud deployment pipelines.',
    salary: { entry: '$75,000', mid: '$108,000', senior: '$148,000' },
    growthRate: '+19%',
    demandLevel: 'high',
    workStyle: 'remote-first',
    timeToReady: '10-14 months',
    keySkills: ['React', 'Node.js', 'TypeScript', 'PostgreSQL', 'Docker', 'AWS'],
    dayInLife: [
      'Design RESTful API routes and database schemas',
      'Develop React UI components consuming server endpoints',
      'Implement JWT/OAuth authentication workflows',
      'Containerize applications with Docker Compose',
      'Deploy full-stack services to cloud platforms',
    ],
    pros: ['Maximum career versatility', 'Ability to build products solo', 'High startup demand'],
    cons: ['Broad surface area to maintain', 'Frequent context switching'],
    companies: ['Stripe', 'GitHub', 'Shopify', 'Cloudflare', 'Supabase'],
    requiredSkillIds: ['html-css', 'javascript', 'react', 'nodejs', 'sql', 'git', 'docker'],
    roadmapId: 'fullstack-developer-roadmap',
  },

  // 9. Backend Engineer
  {
    id: 'backend-engineer',
    subDomainId: 'backend-node',
    domainId: 'backend-development',
    title: 'Backend Engineer',
    emoji: '⚡',
    tagline: 'Engineer high-throughput server systems and APIs',
    description: 'Design distributed architectures, microservices, caching layers, database schemas, and resilient event pipelines.',
    salary: { entry: '$78,000', mid: '$112,000', senior: '$155,000' },
    growthRate: '+21%',
    demandLevel: 'high',
    workStyle: 'remote-first',
    timeToReady: '9-13 months',
    keySkills: ['Node.js', 'Go', 'PostgreSQL', 'Redis', 'Kafka', 'Docker'],
    dayInLife: [
      'Architect relational and NoSQL database schemas',
      'Implement gRPC and RESTful microservices',
      'Optimize database query planners and B-tree indexes',
      'Set up event streams with Apache Kafka',
      'Benchmark API latency and throughput under load',
    ],
    pros: ['Core architecture focus', 'High technical longevity', 'Strong compensation'],
    cons: ['On-call production pager rotations', 'Complex distributed debugging'],
    companies: ['Amazon', 'Uber', 'Twilio', 'Datadog', 'DoorDash'],
    requiredSkillIds: ['nodejs', 'sql', 'docker', 'git'],
    roadmapId: 'backend-engineer-roadmap',
  },

  // 10. Product Designer (UI/UX)
  {
    id: 'product-designer',
    subDomainId: 'product-design',
    domainId: 'ui-ux',
    title: 'Product Designer',
    emoji: '📐',
    tagline: 'Design digital products users fall in love with',
    description: 'Lead user research, create wireframes, establish scalable Figma design systems, and design high-fidelity interactive prototypes.',
    salary: { entry: '$70,000', mid: '$100,000', senior: '$140,000' },
    growthRate: '+18%',
    demandLevel: 'high',
    workStyle: 'hybrid',
    timeToReady: '8-12 months',
    keySkills: ['Figma', 'User Research', 'Prototyping', 'Design Systems', 'Usability Testing'],
    dayInLife: [
      'Conduct user interviews and synthesize pain points',
      'Build wireframes and journey maps in Figma',
      'Maintain design system tokens and component variants',
      'Review engineering implementation for design QA',
      'Present design rationales to product managers',
    ],
    pros: ['High creative impact', 'Direct influence on user satisfaction', 'Growing demand'],
    cons: ['Subjective feedback cycles', 'Balancing user needs with business limits'],
    companies: ['Figma', 'Apple', 'Notion', 'Airbnb', 'Spotify'],
    requiredSkillIds: ['figma', 'ux-research', 'prototyping', 'design-systems'],
    roadmapId: 'product-designer-roadmap',
  },

  // 11. Unity Developer
  {
    id: 'unity-developer',
    subDomainId: 'unity',
    domainId: 'game-development',
    title: 'Unity Game Developer',
    emoji: '🎲',
    tagline: 'Create 2D and 3D games across PC, mobile, and VR',
    description: 'Program game mechanics in C#, design physics interactions, visual shaders, and multiplayer netcode using Unity.',
    salary: { entry: '$65,000', mid: '$92,000', senior: '$125,000' },
    growthRate: '+14%',
    demandLevel: 'moderate',
    workStyle: 'hybrid',
    timeToReady: '10-15 months',
    keySkills: ['C#', 'Unity Engine', 'Game Physics', 'Shader Graph', 'Netcode', 'VR'],
    dayInLife: [
      'Implement player movement and combat mechanics in C#',
      'Build custom visual shaders using Shader Graph',
      'Profile frame rates and optimize draw calls',
      'Integrate 3D assets and animations from artists',
      'Test multiplayer networking and synchronization',
    ],
    pros: ['Fun, deeply creative work', 'Large cross-platform reach', 'Growing VR/AR market'],
    cons: ['Gaming industry crunch culture', 'Lower pay relative to enterprise software'],
    companies: ['EA', 'Niantic', 'Supercell', 'Riot Games', 'Ubisoft'],
    requiredSkillIds: ['csharp', 'unity', 'game-math', 'git'],
    roadmapId: 'unity-developer-roadmap',
  },

  // 12. Ethical Hacker (Cybersecurity)
  {
    id: 'ethical-hacker',
    subDomainId: 'ethical-hacking',
    domainId: 'cyber-security',
    title: 'Ethical Hacker',
    emoji: '💀',
    tagline: 'Offensive security, penetration testing, and vulnerability hunting',
    description: 'Perform authorized penetration tests on networks, APIs, and web apps to discover vulnerabilities before adversaries do.',
    salary: { entry: '$80,000', mid: '$115,000', senior: '$160,000' },
    growthRate: '+31%',
    demandLevel: 'explosive',
    workStyle: 'remote-first',
    timeToReady: '12-18 months',
    keySkills: ['Kali Linux', 'Burp Suite', 'Metasploit', 'Python', 'Networking', 'OSCP'],
    dayInLife: [
      'Perform reconnaissance and port scanning on target scope',
      'Intercept and tamper with HTTP traffic using Burp Suite',
      'Execute privilege escalation exploits in lab environments',
      'Write comprehensive penetration testing reports for clients',
      'Advise engineering teams on vulnerability remediation',
    ],
    pros: ['Exciting problem-solving', 'High job security', 'Huge industry demand'],
    cons: ['Requires strict ethical adherence', 'Constant need to study new exploits'],
    companies: ['CrowdStrike', 'Palo Alto Networks', 'Rapid7', 'Deloitte', 'Mandiant'],
    requiredSkillIds: ['networking', 'linux', 'python', 'web-security', 'oscp'],
    roadmapId: 'ethical-hacker-roadmap',
  },

  // 13. AI Researcher
  {
    id: 'ai-researcher',
    subDomainId: 'ai-research',
    domainId: 'artificial-intelligence',
    title: 'AI Research Scientist',
    emoji: '🧠',
    tagline: 'Pioneer next-generation cognitive models and neural architectures',
    description: 'Conduct foundational research in neural architectures, reinforcement learning, multi-agent systems, and spatial computing.',
    salary: { entry: '$110,000', mid: '$150,000', senior: '$220,000' },
    growthRate: '+40%',
    demandLevel: 'explosive',
    workStyle: 'remote-first',
    timeToReady: '14-20 months',
    keySkills: ['Python', 'PyTorch', 'Linear Algebra', 'Transformers', 'Reinforcement Learning'],
    dayInLife: [
      'Read and implement latest papers from arXiv',
      'Design new attention mechanisms and loss functions',
      'Run multi-GPU training experiments',
      'Evaluate model scaling laws and benchmark results',
      'Publish research findings at NeurIPS and ICML',
    ],
    pros: ['Highest tech compensation', 'Shaping the future of technology', 'Intellectual freedom'],
    cons: ['Requires heavy math and statistical background', 'Research outcomes can be uncertain'],
    companies: ['OpenAI', 'Google DeepMind', 'Anthropic', 'Meta AI', 'Microsoft Research'],
    requiredSkillIds: ['python', 'pytorch', 'statistics', 'linear-algebra'],
    roadmapId: 'ai-researcher-roadmap',
  },

  // 14. Generative AI Engineer
  {
    id: 'genai-engineer',
    subDomainId: 'rag-systems',
    domainId: 'generative-ai',
    title: 'Generative AI Engineer',
    emoji: '✨',
    tagline: 'Build production RAG systems and autonomous AI agents',
    description: 'Engineer enterprise applications powered by LLMs, vector search, embeddings, LangChain, and fine-tuned open-weights models.',
    salary: { entry: '$105,000', mid: '$148,000', senior: '$195,000' },
    growthRate: '+45%',
    demandLevel: 'explosive',
    workStyle: 'remote-first',
    timeToReady: '10-15 months',
    keySkills: ['Python', 'LangChain', 'Vector DBs', 'LlamaIndex', 'Hugging Face', 'LoRA'],
    dayInLife: [
      'Build chunking and embedding pipelines for RAG',
      'Index documents into Pinecone or Milvus vector databases',
      'Fine-tune open LLMs using LoRA and QLoRA',
      'Implement multi-turn agent tool-calling workflows',
      'Benchmark hallucination rates and output guardrails',
    ],
    pros: ['Fastest growing tech specialization', 'Cutting-edge product building', 'High startup demand'],
    cons: ['Ecosystem evolves on a weekly basis', 'Non-deterministic model outputs'],
    companies: ['Cohere', 'Scale AI', 'Perplexity', 'Databricks', 'AWS'],
    requiredSkillIds: ['python', 'pytorch', 'docker', 'git'],
    roadmapId: 'genai-engineer-roadmap',
  },

  // 15. Data Engineer
  {
    id: 'data-engineer',
    subDomainId: 'etl-pipelines',
    domainId: 'data-engineering',
    title: 'Data Engineer',
    emoji: '🗄️',
    tagline: 'Architect real-time streaming and data lakehouse pipelines',
    description: 'Build robust data infrastructure, automated ETL pipelines, distributed Spark jobs, and Snowflake data warehouses.',
    salary: { entry: '$85,000', mid: '$128,000', senior: '$170,000' },
    growthRate: '+30%',
    demandLevel: 'explosive',
    workStyle: 'remote-first',
    timeToReady: '10-14 months',
    keySkills: ['Python', 'SQL', 'Apache Spark', 'Airflow', 'Snowflake', 'Kafka'],
    dayInLife: [
      'Write automated DAGs in Apache Airflow',
      'Process terabytes of event data with PySpark',
      'Build transformed data models using dbt and Snowflake',
      'Manage real-time event streaming with Kafka',
      'Ensure data quality, lineage, and schema governance',
    ],
    pros: ['Critical backbone of every data organization', 'High stability', 'Great compensation'],
    cons: ['Debugging large-scale pipeline failures', 'Handling messy raw data sources'],
    companies: ['Snowflake', 'Databricks', 'Netflix', 'Amazon', 'Palantir'],
    requiredSkillIds: ['python', 'sql', 'docker', 'git'],
    roadmapId: 'data-engineer-roadmap',
  },

  // 16. Cloud Solutions Architect
  {
    id: 'cloud-engineer',
    subDomainId: 'cloud-aws',
    domainId: 'cloud-computing',
    title: 'Cloud Engineer',
    emoji: '☁️',
    tagline: 'Design resilient, scalable multi-cloud infrastructure',
    description: 'Architect secure cloud environments on AWS and Azure using Terraform, serverless functions, VPCs, and IAM policies.',
    salary: { entry: '$85,000', mid: '$126,000', senior: '$168,000' },
    growthRate: '+26%',
    demandLevel: 'high',
    workStyle: 'remote-first',
    timeToReady: '9-14 months',
    keySkills: ['AWS', 'Terraform', 'Linux', 'Docker', 'Networking', 'Python'],
    dayInLife: [
      'Write Infrastructure as Code (IaC) with Terraform',
      'Configure VPC peering, subnets, and security groups',
      'Deploy serverless microservices with AWS Lambda',
      'Audit cloud spending and optimize resource efficiency',
      'Implement multi-region disaster recovery setups',
    ],
    pros: ['Universal corporate demand', 'Clear certification paths', 'High autonomy'],
    cons: ['Complex billing and IAM permissions', 'Security misconfiguration risks'],
    companies: ['Amazon Web Services', 'Microsoft', 'Google Cloud', 'Cisco', 'Accenture'],
    requiredSkillIds: ['docker', 'networking', 'linux', 'git'],
    roadmapId: 'cloud-engineer-roadmap',
  },

  // 17. DevOps Engineer
  {
    id: 'devops-engineer',
    subDomainId: 'cicd-automation',
    domainId: 'devops',
    title: 'DevOps Engineer',
    emoji: '🚀',
    tagline: 'Automate build pipelines and orchestrate Kubernetes clusters',
    description: 'Bridge software engineering and IT operations with CI/CD automation, Kubernetes container orchestration, and Helm deployments.',
    salary: { entry: '$82,000', mid: '$122,000', senior: '$165,000' },
    growthRate: '+27%',
    demandLevel: 'explosive',
    workStyle: 'remote-first',
    timeToReady: '10-15 months',
    keySkills: ['Kubernetes', 'Docker', 'GitHub Actions', 'Terraform', 'Prometheus', 'Linux'],
    dayInLife: [
      'Maintain automated CI/CD build pipelines in GitHub Actions',
      'Manage production Kubernetes clusters and ingress controllers',
      'Set up Prometheus monitoring dashboards and alerts in Grafana',
      'Automate cloud infrastructure with Terraform',
      'Lead post-mortem reviews and reliability enhancements',
    ],
    pros: ['Central to engineering velocity', 'High compensation', 'Always in demand'],
    cons: ['High-stakes production deployments', 'Occasional incident firefighting'],
    companies: ['GitLab', 'Red Hat', 'HashiCorp', 'Spotify', 'Shopify'],
    requiredSkillIds: ['docker', 'linux', 'git'],
    roadmapId: 'devops-engineer-roadmap',
  },

  // 18. Database Administrator (DBA)
  {
    id: 'database-administrator',
    subDomainId: 'sql-tuning',
    domainId: 'database-bigdata',
    title: 'Database Administrator',
    emoji: '💾',
    tagline: 'Master database performance, replication, and data integrity',
    description: 'Administer relational and NoSQL databases, optimize query planners, manage replication clusters, and execute backups.',
    salary: { entry: '$76,000', mid: '$115,000', senior: '$152,000' },
    growthRate: '+18%',
    demandLevel: 'high',
    workStyle: 'hybrid',
    timeToReady: '9-13 months',
    keySkills: ['PostgreSQL', 'MySQL', 'MongoDB', 'Redis', 'SQL Tuning', 'Linux'],
    dayInLife: [
      'Tune slow queries using EXPLAIN ANALYZE',
      'Configure primary-replica replication and automated failover',
      'Manage high-volume database migrations',
      'Enforce role-based access control and database encryption',
      'Design disaster recovery backup strategies',
    ],
    pros: ['High job security', 'Essential enterprise role', 'Well-defined domain'],
    cons: ['Stressful recovery during database outages', 'Strict maintenance windows'],
    companies: ['Oracle', 'MongoDB', 'IBM', 'JPMorgan Chase', 'Salesforce'],
    requiredSkillIds: ['sql', 'linux', 'git'],
    roadmapId: 'database-administrator-roadmap',
  },

  // 19. Blockchain Developer
  {
    id: 'blockchain-developer',
    subDomainId: 'smart-contracts',
    domainId: 'blockchain-web3',
    title: 'Blockchain & Smart Contract Developer',
    emoji: '⛓️',
    tagline: 'Build secure decentralized apps and smart contracts',
    description: 'Write, test, and audit EVM smart contracts in Solidity and build Web3 dApps using Ethers.js, Hardhat, and Foundry.',
    salary: { entry: '$90,000', mid: '$135,000', senior: '$185,000' },
    growthRate: '+25%',
    demandLevel: 'high',
    workStyle: 'remote-first',
    timeToReady: '10-15 months',
    keySkills: ['Solidity', 'Ethereum', 'Hardhat', 'Ethers.js', 'Web3', 'TypeScript'],
    dayInLife: [
      'Write Solidity smart contracts with OpenZeppelin libraries',
      'Perform gas optimization audits on contract functions',
      'Write comprehensive unit tests with Foundry and Hardhat',
      'Build frontends that connect to MetaMask and Web3 wallets',
      'Deploy contracts to Ethereum and Layer-2 networks',
    ],
    pros: ['High compensation', 'Global remote-first culture', 'Pioneering open financial rails'],
    cons: ['Smart contract bugs are irreversible', 'Market cyclicality'],
    companies: ['ConsenSys', 'Chainlink', 'Uniswap', 'Polygon', 'OpenSea'],
    requiredSkillIds: ['javascript', 'typescript', 'git'],
    roadmapId: 'blockchain-developer-roadmap',
  },

  // 20. Embedded Systems & IoT Engineer
  {
    id: 'embedded-engineer',
    subDomainId: 'embedded-firmware',
    domainId: 'iot-embedded',
    title: 'Embedded Systems Engineer',
    emoji: '📡',
    tagline: 'Write the software that brings hardware to life',
    description: 'Develop low-level C/C++ firmware, FreeRTOS drivers, and IoT communication protocols for microcontrollers and edge hardware.',
    salary: { entry: '$72,000', mid: '$104,000', senior: '$142,000' },
    growthRate: '+20%',
    demandLevel: 'high',
    workStyle: 'hybrid',
    timeToReady: '11-16 months',
    keySkills: ['C', 'C++', 'ARM Cortex', 'FreeRTOS', 'I2C/SPI', 'MQTT'],
    dayInLife: [
      'Write device drivers in C for ARM Cortex microcontrollers',
      'Debug hardware timing signals with logic analyzers and oscilloscopes',
      'Implement power-saving sleep modes for battery-powered sensors',
      'Transmit sensor telemetry over MQTT and Bluetooth LE',
      'Flash firmware updates and conduct hardware reliability tests',
    ],
    pros: ['Work directly with physical hardware', 'High longevity', 'Growing robotics and IoT market'],
    cons: ['Requires access to physical lab hardware', 'Strict memory and resource constraints'],
    companies: ['Tesla', 'Qualcomm', 'Bosch', 'Texas Instruments', 'Apple'],
    requiredSkillIds: ['linux', 'git'],
    roadmapId: 'embedded-engineer-roadmap',
  },

  // 21. Network Engineer
  {
    id: 'network-engineer',
    subDomainId: 'routing-switching',
    domainId: 'computer-networks',
    title: 'Network Engineer',
    emoji: '🌐',
    tagline: 'Design enterprise network architectures and routing topologies',
    description: 'Configure routers, switches, firewalls, BGP routing protocols, VPNs, and automate networks with Python.',
    salary: { entry: '$68,000', mid: '$98,000', senior: '$135,000' },
    growthRate: '+16%',
    demandLevel: 'high',
    workStyle: 'hybrid',
    timeToReady: '8-12 months',
    keySkills: ['Cisco CCNA', 'Routing & Switching', 'TCP/IP', 'BGP', 'Firewalls', 'Python'],
    dayInLife: [
      'Configure enterprise Cisco/Juniper routing tables',
      'Diagnose packet drops and latency issues with Wireshark',
      'Set up site-to-site IPsec VPN tunnels',
      'Automate switch configurations using Python scripts',
      'Upgrade core network switch firmware during maintenance windows',
    ],
    pros: ['Foundational pillar of modern IT', 'Clear industry certifications', 'High job stability'],
    cons: ['Physical datacenter work occasionally required', 'High-pressure outage resolution'],
    companies: ['Cisco', 'Juniper Networks', 'AT&T', 'Verizon', 'Akamai'],
    requiredSkillIds: ['networking', 'linux', 'git'],
    roadmapId: 'network-engineer-roadmap',
  },

  // 22. QA Automation Engineer (SDET)
  {
    id: 'qa-automation-engineer',
    subDomainId: 'test-automation',
    domainId: 'software-testing-qa',
    title: 'QA Automation Engineer (SDET)',
    emoji: '🔍',
    tagline: 'Build bulletproof automated test frameworks and suites',
    description: 'Design end-to-end automated testing frameworks using Playwright, Cypress, and k6 to guarantee software quality.',
    salary: { entry: '$68,000', mid: '$96,000', senior: '$132,000' },
    growthRate: '+17%',
    demandLevel: 'high',
    workStyle: 'remote-first',
    timeToReady: '6-10 months',
    keySkills: ['Playwright', 'Cypress', 'TypeScript', 'Selenium', 'CI/CD', 'k6'],
    dayInLife: [
      'Write end-to-end regression tests in Playwright and TypeScript',
      'Integrate test execution into automated GitHub Actions pipelines',
      'Execute load and stress tests with k6',
      'Analyze test report failures and log detailed bug reports',
      'Collaborate with developers on testability and mock APIs',
    ],
    pros: ['High demand across all software teams', 'Great remote opportunities', 'Rapid entry into tech'],
    cons: ['Maintaining flaky E2E tests can be tedious', 'Fast release cycles demand quick turnaround'],
    companies: ['Microsoft', 'Salesforce', 'Amazon', 'HubSpot', 'Adyen'],
    requiredSkillIds: ['javascript', 'typescript', 'git'],
    roadmapId: 'qa-automation-engineer-roadmap',
  },

  // 23. Business Intelligence & Data Analyst
  {
    id: 'business-analyst',
    subDomainId: 'bi-dashboards',
    domainId: 'data-analytics',
    title: 'Business & Data Analyst',
    emoji: '📈',
    tagline: 'Translate complex datasets into executive business strategies',
    description: 'Build executive KPI dashboards in PowerBI and Tableau, query databases with SQL, and analyze conversion funnels.',
    salary: { entry: '$65,000', mid: '$94,000', senior: '$128,000' },
    growthRate: '+23%',
    demandLevel: 'high',
    workStyle: 'hybrid',
    timeToReady: '6-10 months',
    keySkills: ['PowerBI', 'Tableau', 'SQL', 'Excel', 'Data Visualization', 'Python'],
    dayInLife: [
      'Write SQL queries to aggregate sales and product metrics',
      'Design interactive executive dashboards in PowerBI',
      'Analyze customer retention and churn cohorts',
      'Prepare weekly performance briefing presentations',
      'Partner with business leaders on revenue projections',
    ],
    pros: ['Direct visibility with senior leadership', 'Applicable in every commercial industry', 'Accessible entry barrier'],
    cons: ['Ad-hoc reporting requests', 'Explaining technical numbers to non-technical stakeholders'],
    companies: ['McKinsey', 'Boston Consulting Group', 'Amazon', 'Target', 'Nike'],
    requiredSkillIds: ['sql', 'visualization'],
    roadmapId: 'business-analyst-roadmap',
  },

  // 24. Security Analyst (SOC)
  {
    id: 'security-analyst',
    subDomainId: 'soc-defense',
    domainId: 'cyber-security',
    title: 'Security Operations Analyst',
    emoji: '🛡️',
    tagline: 'Monitor, detect, and defend against enterprise cyber threats',
    description: 'Monitor Security Operations Center (SOC) telemetry, investigate alerts with SIEM tools, and execute incident response playbooks.',
    salary: { entry: '$72,000', mid: '$105,000', senior: '$145,000' },
    growthRate: '+33%',
    demandLevel: 'explosive',
    workStyle: 'remote-first',
    timeToReady: '8-12 months',
    keySkills: ['SIEM (Splunk)', 'Incident Response', 'Wireshark', 'Threat Hunting', 'Linux', 'Network Security'],
    dayInLife: [
      'Triage real-time alerts in Splunk and Microsoft Sentinel',
      'Analyze malicious phishing emails and quarantined files',
      'Inspect network packet captures for signs of data exfiltration',
      'Coordinate incident containment with IT infrastructure teams',
      'Update firewall rules and threat intelligence blocklists',
    ],
    pros: ['Crucial defensive role', 'High hiring demand', 'Clear progression to Security Engineering'],
    cons: ['Alert fatigue in busy SOCs', 'Shift work in 24/7 security centers'],
    companies: ['Microsoft', 'CrowdStrike', 'Cisco Talos', 'Palo Alto Networks', 'FireEye'],
    requiredSkillIds: ['networking', 'linux', 'web-security'],
    roadmapId: 'security-analyst-roadmap',
  },
];
