export const rawNews = [
  {
    id: 'news-and-1',
    title: 'Android Studio Ladybug Feature Drop Released',
    description:
      'Google has released Android Studio Ladybug Feature Drop with major Gemini AI integrations, new UI components, and significantly improved build speeds up to 40% faster.',
    source: 'Android Developers Blog',
    publishedAt: new Date('2026-08-28T09:00:00Z'),
    url: 'https://android-developers.googleblog.com',
    imageEmoji: '🤖',
    tags: ['android studio', 'kotlin', 'android'],
    careerIds: ['android-developer'],
    isBreaking: true,
  },
  {
    id: 'news-and-2',
    title: 'Jetpack Compose 1.8 Brings Adaptive Layouts',
    description:
      'The latest Jetpack Compose update introduces first-class adaptive layout support for foldables, tablets, and large screens, making multi-device development easier.',
    source: 'Google Developers',
    publishedAt: new Date('2026-08-25T12:00:00Z'),
    url: 'https://developer.android.com',
    imageEmoji: '🎨',
    tags: ['jetpack', 'compose', 'android', 'ui'],
    careerIds: ['android-developer'],
    isBreaking: false,
  },
  {
    id: 'news-and-3',
    title: 'Kotlin 2.1 Performance Improvements Benchmarked',
    description:
      'Kotlin 2.1 shows up to 30% improvement in compilation speed and introduces new K2 compiler features. Benchmarks across real-world projects show consistent gains.',
    source: 'Kotlin Blog',
    publishedAt: new Date('2026-08-22T08:00:00Z'),
    url: 'https://kotlinlang.org/blog',
    imageEmoji: '⚡',
    tags: ['kotlin', 'performance', 'compiler'],
    careerIds: ['android-developer'],
    isBreaking: false,
  },
  {
    id: 'news-and-4',
    title: 'Android Developer Jobs Up 23% in Q3 2026',
    description:
      'Industry reports show Android developer job postings increased 23% year-over-year in Q3 2026, with Kotlin and Compose expertise commanding premium salaries.',
    source: 'LinkedIn Career Insights',
    publishedAt: new Date('2026-08-20T10:00:00Z'),
    url: 'https://linkedin.com/jobs',
    imageEmoji: '📈',
    tags: ['android', 'jobs', 'career', 'mobile'],
    careerIds: ['android-developer'],
    isBreaking: false,
  },
  {
    id: 'news-ai-1',
    title: 'GPT-5 Architecture Details Revealed',
    description:
      "OpenAI shares insights into GPT-5's mixture-of-experts architecture, showing how specialized modules handle different types of reasoning tasks.",
    source: 'OpenAI Research',
    publishedAt: new Date('2026-08-29T10:00:00Z'),
    url: 'https://openai.com/research',
    imageEmoji: '🧠',
    tags: ['ai', 'llm', 'openai', 'machine learning'],
    careerIds: ['ml-engineer', 'data-scientist'],
    isBreaking: true,
  },
  {
    id: 'news-ai-2',
    title: 'PyTorch 2.5 Brings Native Apple Silicon Support',
    description:
      'PyTorch 2.5 introduces native Metal Performance Shaders support for Apple Silicon, enabling 3x faster training on Mac devices.',
    source: 'PyTorch Blog',
    publishedAt: new Date('2026-08-26T09:00:00Z'),
    url: 'https://pytorch.org/blog',
    imageEmoji: '🔥',
    tags: ['pytorch', 'machine learning', 'deep learning'],
    careerIds: ['ml-engineer', 'data-scientist'],
    isBreaking: false,
  },
  {
    id: 'news-ai-3',
    title: 'ML Engineer Salaries Hit Record Highs',
    description:
      'Machine learning engineers are commanding record salaries, with senior roles averaging $250K+ in tech hubs. Demand continues to outpace supply.',
    source: 'Levels.fyi',
    publishedAt: new Date('2026-08-23T08:00:00Z'),
    url: 'https://levels.fyi',
    imageEmoji: '💰',
    tags: ['ai', 'machine learning', 'career', 'salary'],
    careerIds: ['ml-engineer', 'data-scientist'],
    isBreaking: false,
  },
  {
    id: 'news-fe-1',
    title: 'React 20 RC Released with Server Components by Default',
    description:
      'React 20 Release Candidate ships with Server Components enabled by default, new concurrent features, and the removal of legacy class component lifecycle methods.',
    source: 'React Blog',
    publishedAt: new Date('2026-08-28T14:00:00Z'),
    url: 'https://react.dev/blog',
    imageEmoji: '⚛️',
    tags: ['react', 'web', 'javascript', 'frontend'],
    careerIds: ['frontend-developer', 'fullstack-developer'],
    isBreaking: true,
  },
  {
    id: 'news-fe-2',
    title: 'Next.js 16 Introduces Partial Prerendering GA',
    description:
      'Next.js 16 ships Partial Prerendering (PPR) as a stable feature, combining static and dynamic content at a route level for optimal performance.',
    source: 'Vercel Blog',
    publishedAt: new Date('2026-08-25T11:00:00Z'),
    url: 'https://vercel.com/blog',
    imageEmoji: '▲',
    tags: ['nextjs', 'react', 'web', 'frontend', 'typescript'],
    careerIds: ['frontend-developer', 'fullstack-developer'],
    isBreaking: false,
  },
  {
    id: 'news-fe-3',
    title: 'TypeScript 5.8 Improves Type Inference',
    description:
      'TypeScript 5.8 introduces smarter type narrowing, conditional type inference improvements, and faster language server performance.',
    source: 'TypeScript Blog',
    publishedAt: new Date('2026-08-21T09:00:00Z'),
    url: 'https://devblogs.microsoft.com/typescript',
    imageEmoji: '📘',
    tags: ['typescript', 'web', 'javascript', 'frontend'],
    careerIds: ['frontend-developer', 'fullstack-developer'],
    isBreaking: false,
  },
  {
    id: 'news-devops-1',
    title: 'Kubernetes 1.33 Releases with Native AI Workload Scheduling',
    description:
      'Kubernetes 1.33 introduces native scheduling hints for AI/ML workloads, GPU fractioning support, and improved autoscaling for LLM inference pods.',
    source: 'CNCF Blog',
    publishedAt: new Date('2026-08-27T10:00:00Z'),
    url: 'https://kubernetes.io/blog',
    imageEmoji: '☸️',
    tags: ['kubernetes', 'devops', 'cloud', 'docker'],
    careerIds: ['devops-engineer', 'cloud-architect'],
    isBreaking: false,
  },
  {
    id: 'news-sec-1',
    title: 'Zero-Day Vulnerability Found in Popular npm Packages',
    description:
      'Security researchers discovered a critical zero-day in three widely-used npm packages with over 500M weekly downloads. Patches are available — update immediately.',
    source: 'Security Week',
    publishedAt: new Date('2026-08-29T08:00:00Z'),
    url: 'https://securityweek.com',
    imageEmoji: '🔐',
    tags: ['security', 'vulnerability', 'cybersecurity'],
    careerIds: ['security-engineer'],
    isBreaking: true,
  },
  {
    id: 'news-gen-1',
    title: 'GitHub Copilot Adds Multi-File Context Window',
    description:
      "GitHub Copilot's new multi-file context feature allows the AI to understand your entire codebase structure when making suggestions, dramatically improving accuracy.",
    source: 'GitHub Blog',
    publishedAt: new Date('2026-08-28T16:00:00Z'),
    url: 'https://github.blog',
    imageEmoji: '🐙',
    tags: ['ai', 'github', 'developer tools', 'coding'],
    careerIds: [],
    isBreaking: false,
  },
  {
    id: 'news-gen-2',
    title: 'Stack Overflow Developer Survey 2026 Results',
    description:
      'The annual Stack Overflow survey reveals TypeScript overtaking JavaScript as most-used language, Rust staying most admired, and AI tools used by 85% of developers.',
    source: 'Stack Overflow',
    publishedAt: new Date('2026-08-20T12:00:00Z'),
    url: 'https://survey.stackoverflow.co',
    imageEmoji: '📊',
    tags: ['technology', 'developer', 'career', 'programming'],
    careerIds: [],
    isBreaking: false,
  },
];
