export const rawProjects = [
  {
    id: 'hello-android',
    title: 'Hello World App',
    description: 'Your first Android app. Set up the development environment and ship something to your emulator.',
    longDescription: 'The classic Hello World, but for Android. You\'ll set up Android Studio, create your first project, understand the manifest, and run your app on the emulator. This is about getting comfortable with the toolchain.',
    emoji: '👋',
    difficulty: 'starter',
    estimatedTime: '2 days',
    skillIds: ['kotlin', 'android-sdk'],
    careerIds: ['android-developer'],
    tags: ['starter', 'android', 'setup'],
    objectives: ['Setup Android Studio', 'Create first project', 'Run on emulator', 'Understand project structure'],
    techStack: ['Kotlin', 'Android SDK', 'Android Studio'],
    status: 'completed',
    isPortfolioWorthy: false,
    phase: 1,
  },
  {
    id: 'weather-app',
    title: 'Weather App',
    description: 'Fetch real weather data from an API and display it beautifully on Android.',
    longDescription: 'Build a weather application that fetches real-time data from a weather API. You\'ll learn Retrofit for networking, handle JSON parsing with Kotlin serialization, implement error states, and display data with clean Compose UI.',
    emoji: '🌤️',
    difficulty: 'intermediate',
    estimatedTime: '2 weeks',
    skillIds: ['kotlin', 'jetpack-compose', 'android-sdk'],
    careerIds: ['android-developer'],
    tags: ['android', 'networking', 'api', 'retrofit'],
    objectives: ['Implement Retrofit for API calls', 'Handle loading/error states', 'Build weather UI with Compose', 'Add location permissions'],
    techStack: ['Kotlin', 'Jetpack Compose', 'Retrofit', 'OpenWeatherMap API'],
    status: 'not-started',
    isPortfolioWorthy: true,
    phase: 2,
  },
  {
    id: 'notes-app',
    title: 'Notes App with Room DB',
    description: 'Offline-first notes app with local database, search, and categories.',
    longDescription: 'A complete CRUD notes application using Room for local persistence. Features include creating, editing, deleting, and searching notes. You\'ll implement MVVM architecture, Room database with DAO pattern, and LiveData/Flow for reactive UI updates.',
    emoji: '📝',
    difficulty: 'intermediate',
    estimatedTime: '3 weeks',
    skillIds: ['kotlin', 'jetpack-compose', 'android-sdk'],
    careerIds: ['android-developer'],
    tags: ['android', 'room', 'crud', 'mvvm', 'database'],
    objectives: ['Setup Room database', 'Implement MVVM with ViewModel', 'Build CRUD operations', 'Add search functionality', 'Implement category filters'],
    techStack: ['Kotlin', 'Jetpack Compose', 'Room', 'ViewModel', 'LiveData'],
    status: 'not-started',
    isPortfolioWorthy: true,
    phase: 2,
  },
  {
    id: 'capstone-android',
    title: 'Social Photo App (Play Store Ready)',
    description: 'A production-quality photo sharing app. The capstone project for your Android portfolio.',
    longDescription: 'Build a feature-rich photo sharing app with Firebase backend, user authentication, photo upload, social feed, likes, and comments. This is portfolio-level work that demonstrates production-quality Android engineering.',
    emoji: '📸',
    difficulty: 'capstone',
    estimatedTime: '5 weeks',
    skillIds: ['kotlin', 'jetpack-compose', 'android-sdk', 'git', 'firebase-basics'],
    careerIds: ['android-developer'],
    tags: ['android', 'firebase', 'social', 'photos', 'portfolio', 'capstone'],
    objectives: ['Firebase authentication', 'Cloud Storage for photos', 'Firestore social feed', 'Push notifications', 'Deploy to Play Store'],
    techStack: ['Kotlin', 'Jetpack Compose', 'Firebase', 'Hilt', 'Coroutines', 'Room'],
    status: 'not-started',
    isPortfolioWorthy: true,
    phase: 4,
  },
  {
    id: 'ui-clone',
    title: 'Popular App UI Clone',
    description: 'Clone the UI of a famous app — Instagram, Spotify, or WhatsApp — using Jetpack Compose.',
    longDescription: 'Challenge yourself to pixel-perfectly recreate the UI of a popular app using Jetpack Compose. This develops your eye for design and pushes your Compose skills to the limit. Great for learning complex layouts and animations.',
    emoji: '🎨',
    difficulty: 'intermediate',
    estimatedTime: '10 days',
    skillIds: ['kotlin', 'jetpack-compose'],
    careerIds: ['android-developer'],
    tags: ['android', 'compose', 'ui', 'clone', 'design'],
    objectives: ['Recreate bottom navigation', 'Implement scrollable feeds', 'Build profile screens', 'Add animations with Compose'],
    techStack: ['Kotlin', 'Jetpack Compose', 'Coil (image loading)', 'Navigation Compose'],
    status: 'not-started',
    isPortfolioWorthy: false,
    phase: 2,
  },
  {
    id: 'titanic-kaggle',
    title: 'Titanic — Kaggle Competition',
    description: 'Your first ML competition. Predict survival on the Titanic using machine learning.',
    longDescription: 'The quintessential first Kaggle competition. You\'ll clean data, engineer features, train multiple classification models, and optimize your predictions. This project teaches the complete ML workflow from raw data to submission.',
    emoji: '🚢',
    difficulty: 'starter',
    estimatedTime: '1 week',
    skillIds: ['python', 'pandas', 'statistics'],
    careerIds: ['ml-engineer', 'data-scientist'],
    tags: ['ml', 'kaggle', 'classification', 'eda', 'beginner'],
    objectives: ['Exploratory data analysis', 'Feature engineering', 'Train classification models', 'Submit to Kaggle leaderboard'],
    techStack: ['Python', 'Pandas', 'Scikit-learn', 'Seaborn', 'Jupyter Notebook'],
    status: 'completed',
    isPortfolioWorthy: false,
    phase: 1,
  },
  {
    id: 'image-classifier',
    title: 'Custom Image Classifier',
    description: 'Train a neural network to classify your own custom dataset of images.',
    longDescription: 'Build and train a convolutional neural network on a custom dataset you collect yourself. You\'ll learn transfer learning, data augmentation, model evaluation, and how to deploy your model as a simple web API.',
    emoji: '👁️',
    difficulty: 'intermediate',
    estimatedTime: '3 weeks',
    skillIds: ['python', 'pytorch', 'tensorflow'],
    careerIds: ['ml-engineer'],
    tags: ['deep-learning', 'cnn', 'image-classification', 'pytorch'],
    objectives: ['Collect and label custom dataset', 'Fine-tune pretrained model', 'Achieve >90% validation accuracy', 'Deploy model as REST API'],
    techStack: ['Python', 'PyTorch', 'FastAPI', 'Pillow', 'Weights & Biases'],
    status: 'not-started',
    isPortfolioWorthy: true,
    phase: 3,
  },
  {
    id: 'ml-capstone-project',
    title: 'Full ML Pipeline: End-to-End',
    description: 'Build a complete ML system from raw data collection to monitored production deployment.',
    longDescription: 'The capstone ML project: design, build, and deploy a complete machine learning system. Includes a data pipeline, model training with experiment tracking, model serving with FastAPI, monitoring with Grafana, and a simple frontend.',
    emoji: '🤖',
    difficulty: 'capstone',
    estimatedTime: '6 weeks',
    skillIds: ['python', 'pytorch', 'tensorflow', 'docker', 'statistics'],
    careerIds: ['ml-engineer'],
    tags: ['mlops', 'deployment', 'production', 'monitoring', 'capstone'],
    objectives: ['Build data pipeline', 'Train and track experiments with MLflow', 'Serve model with FastAPI', 'Containerize with Docker', 'Monitor with Evidently AI'],
    techStack: ['Python', 'PyTorch', 'MLflow', 'FastAPI', 'Docker', 'PostgreSQL'],
    status: 'not-started',
    isPortfolioWorthy: true,
    phase: 4,
  },
  {
    id: 'landing-page',
    title: 'Pixel-Perfect Landing Page',
    description: 'Clone a stunning landing page from the web, pixel-perfect, using only HTML and CSS.',
    longDescription: 'Challenge yourself to recreate a high-quality landing page from a real company (Apple, Linear, Stripe, etc.) using only HTML and CSS. No frameworks. This develops precision, attention to detail, and deep CSS knowledge.',
    emoji: '🌐',
    difficulty: 'starter',
    estimatedTime: '3 days',
    skillIds: ['html-css'],
    careerIds: ['frontend-developer'],
    tags: ['html', 'css', 'responsive', 'starter'],
    objectives: ['Match design pixel-perfectly', 'Implement responsive layout', 'Add hover animations', 'Achieve good Lighthouse score'],
    techStack: ['HTML', 'CSS', 'Figma (for measuring)'],
    status: 'completed',
    isPortfolioWorthy: false,
    phase: 1,
  },
  {
    id: 'portfolio-site',
    title: 'Developer Portfolio Website',
    description: 'Build your personal portfolio with React and Next.js. The most important website you\'ll ever make.',
    longDescription: 'Design and build your personal developer portfolio. Feature your projects, tell your story, and make a lasting first impression on potential employers. This is built with Next.js, Tailwind CSS, and deployed on Vercel.',
    emoji: '🧑‍💻',
    difficulty: 'intermediate',
    estimatedTime: '2 weeks',
    skillIds: ['react', 'typescript', 'html-css'],
    careerIds: ['frontend-developer', 'fullstack-developer'],
    tags: ['portfolio', 'nextjs', 'personal', 'deployment'],
    objectives: ['Design personal brand', 'Build with Next.js App Router', 'Add smooth animations', 'Deploy to Vercel', 'SEO optimize'],
    techStack: ['React', 'Next.js', 'Tailwind CSS', 'Framer Motion', 'Vercel'],
    status: 'not-started',
    isPortfolioWorthy: true,
    phase: 4,
  },
];
