export interface RawProject {
  id: string;
  title: string;
  description: string;
  longDescription: string;
  emoji: string;
  difficulty: 'starter' | 'intermediate' | 'advanced' | 'capstone';
  estimatedTime: string;
  skillIds: string[];
  careerIds: string[];
  tags: string[];
  objectives: string[];
  techStack: string[];
  status: 'not-started' | 'in-progress' | 'completed' | 'published';
  isPortfolioWorthy: boolean;
  phase: number;
}

export const rawProjects: RawProject[] = [
  // Full Stack Developer
  {
    id: 'proj-fs-ecommerce',
    title: 'Full-Stack E-Commerce SaaS',
    description: 'Production e-commerce platform with Stripe payments, auth, and order tracking.',
    longDescription: 'Build an end-to-end e-commerce store with product catalogs, shopping cart, Stripe payment webhooks, user orders, and an admin analytics dashboard.',
    emoji: '🛍️',
    difficulty: 'intermediate',
    estimatedTime: '3 weeks',
    skillIds: ['react', 'nodejs', 'sql', 'typescript'],
    careerIds: ['fullstack-developer'],
    tags: ['fullstack', 'react', 'stripe', 'nodejs'],
    objectives: ['Implement JWT auth', 'Integrate Stripe checkout', 'PostgreSQL database modeling', 'Build responsive cart UI'],
    techStack: ['React', 'Node.js', 'Express', 'PostgreSQL', 'Stripe API'],
    status: 'not-started',
    isPortfolioWorthy: true,
    phase: 2,
  },
  {
    id: 'proj-fs-capstone',
    title: 'Real-Time Collaboration Workspace',
    description: 'Notion/Linear-style collaborative workspace with WebSockets, rich text, and team permissions.',
    longDescription: 'Complete SaaS workspace with multi-user real-time cursor tracking, live document editing via WebSockets, role-based team workspaces, and cloud file uploads.',
    emoji: '🚀',
    difficulty: 'capstone',
    estimatedTime: '5 weeks',
    skillIds: ['react', 'nodejs', 'docker', 'sql', 'typescript'],
    careerIds: ['fullstack-developer'],
    tags: ['capstone', 'websockets', 'saas', 'fullstack'],
    objectives: ['Deploy real-time WebSockets', 'Build multi-tenant RBAC', 'Containerize with Docker', 'Deploy to AWS EC2'],
    techStack: ['React 19', 'Node.js', 'Socket.io', 'PostgreSQL', 'Docker', 'AWS'],
    status: 'not-started',
    isPortfolioWorthy: true,
    phase: 4,
  },

  // Frontend Developer
  {
    id: 'proj-fe-dashboard',
    title: 'SaaS Analytics Dashboard',
    description: 'Interactive analytics dashboard with charts, dark mode, and responsive layout.',
    longDescription: 'Modern dashboard interface featuring dynamic time-series charts, filtering, customizable widget grids, keyboard shortcuts, and Lighthouse 100 performance.',
    emoji: '📊',
    difficulty: 'intermediate',
    estimatedTime: '2 weeks',
    skillIds: ['react', 'typescript', 'html-css'],
    careerIds: ['frontend-developer'],
    tags: ['frontend', 'react', 'tailwind', 'charts'],
    objectives: ['Responsive Tailwind layout', 'TanStack Query data caching', 'Interactive charting', 'Accessible UI elements'],
    techStack: ['React', 'TypeScript', 'Tailwind CSS', 'Recharts', 'TanStack Query'],
    status: 'not-started',
    isPortfolioWorthy: true,
    phase: 2,
  },
  {
    id: 'proj-fe-capstone',
    title: 'High-Performance Headless Storefront',
    description: 'Production Next.js 15 web app with Server Components and sub-second page loads.',
    longDescription: 'Full production web application utilizing Next.js App Router, React Server Components, streaming SSR, localized routing, and Core Web Vitals optimization.',
    emoji: '⚡',
    difficulty: 'capstone',
    estimatedTime: '4 weeks',
    skillIds: ['react', 'typescript', 'html-css', 'javascript'],
    careerIds: ['frontend-developer'],
    tags: ['nextjs', 'performance', 'frontend', 'capstone'],
    objectives: ['Implement React Server Components', 'Optimize LCP and CLS scores', 'Write automated Playwright tests', 'Deploy to Vercel with preview stages'],
    techStack: ['Next.js 15', 'TypeScript', 'Tailwind CSS', 'Playwright', 'Vercel'],
    status: 'not-started',
    isPortfolioWorthy: true,
    phase: 4,
  },

  // Backend Engineer
  {
    id: 'proj-be-rate-limiter',
    title: 'Distributed Rate Limiter & URL Engine',
    description: 'High-throughput URL shortening service with sliding-window Redis rate limiting.',
    longDescription: 'Design a distributed backend service capable of handling 50,000 req/s. Implement sliding window token bucket rate limiting in Redis, custom Base62 encoding, and PostgreSQL analytics.',
    emoji: '⚡',
    difficulty: 'intermediate',
    estimatedTime: '2 weeks',
    skillIds: ['nodejs', 'sql'],
    careerIds: ['backend-engineer'],
    tags: ['backend', 'redis', 'distributed-systems', 'api'],
    objectives: ['Design distributed Redis rate limiter', 'Benchmark with k6 under high concurrency', 'Implement database connection pooling', 'Write automated unit test suite'],
    techStack: ['Node.js', 'TypeScript', 'Redis', 'PostgreSQL', 'k6'],
    status: 'not-started',
    isPortfolioWorthy: true,
    phase: 2,
  },
  {
    id: 'proj-be-capstone',
    title: 'Real-Time Order Matching Engine API',
    description: 'Financial exchange matching engine with gRPC microservices and Kafka event stream.',
    longDescription: 'Production-ready financial order book matching engine. Features in-memory order matching, binary gRPC communication, Kafka audit logging, and zero data loss transaction handling.',
    emoji: '📈',
    difficulty: 'capstone',
    estimatedTime: '5 weeks',
    skillIds: ['nodejs', 'sql', 'docker'],
    careerIds: ['backend-engineer'],
    tags: ['backend', 'grpc', 'kafka', 'capstone'],
    objectives: ['Implement in-memory order book algorithm', 'Build gRPC microservice communication', 'Set up Kafka event streaming', 'Deploy on Kubernetes with monitoring'],
    techStack: ['Go / Node.js', 'gRPC', 'Apache Kafka', 'PostgreSQL', 'Docker', 'Kubernetes'],
    status: 'not-started',
    isPortfolioWorthy: true,
    phase: 4,
  },

  // Android Developer
  {
    id: 'proj-android-news',
    title: 'Offline-First News Reader',
    description: 'Jetpack Compose Android app with Room database and Retrofit network caching.',
    longDescription: 'Modern Android application consuming top news APIs. Implements MVVM architecture, Room database caching for offline reading, Coroutines Flow, and Material 3 design.',
    emoji: '📰',
    difficulty: 'intermediate',
    estimatedTime: '3 weeks',
    skillIds: ['kotlin', 'jetpack-compose', 'android-sdk'],
    careerIds: ['android-developer'],
    tags: ['android', 'kotlin', 'compose', 'room'],
    objectives: ['Build declarative Compose UI', 'Implement Room DAO repository pattern', 'Consume REST API with Retrofit', 'Handle network connectivity changes'],
    techStack: ['Kotlin', 'Jetpack Compose', 'Room', 'Retrofit', 'Coroutines'],
    status: 'not-started',
    isPortfolioWorthy: true,
    phase: 2,
  },
  {
    id: 'proj-android-capstone',
    title: 'Social Fitness Tracker (Play Store App)',
    description: 'Production Android app with Google Maps GPS tracking, WorkManager sync, and Play Store release.',
    longDescription: 'End-to-end native Android application with background GPS workout tracking using WorkManager, custom Jetpack Compose charts, and automated Google Play Store release pipeline.',
    emoji: '🏃',
    difficulty: 'capstone',
    estimatedTime: '5 weeks',
    skillIds: ['kotlin', 'jetpack-compose', 'android-sdk', 'git'],
    careerIds: ['android-developer'],
    tags: ['android', 'capstone', 'playstore', 'kotlin'],
    objectives: ['Implement foreground service GPS tracking', 'Hilt dependency injection setup', 'Unit test ViewModels with Mockk', 'Generate signed Play Store App Bundle'],
    techStack: ['Kotlin', 'Jetpack Compose', 'Hilt', 'Room', 'WorkManager', 'Google Maps SDK'],
    status: 'not-started',
    isPortfolioWorthy: true,
    phase: 4,
  },

  // iOS Developer
  {
    id: 'proj-ios-habits',
    title: 'SwiftUI Habit Tracker & Widgets',
    description: 'iOS application with interactive iOS 18 Home Screen widgets and SwiftData.',
    longDescription: 'Create a clean, fluid iOS app to track daily habits with streak counters, SwiftData local persistence, custom animations, and interactive WidgetKit timeline widgets.',
    emoji: '📱',
    difficulty: 'intermediate',
    estimatedTime: '3 weeks',
    skillIds: ['swift', 'swiftui', 'xcode'],
    careerIds: ['ios-developer'],
    tags: ['ios', 'swift', 'swiftui', 'widgets'],
    objectives: ['Design declarative SwiftUI screens', 'Implement SwiftData persistence', 'Build WidgetKit interactive widgets', 'Support dark mode and Dynamic Type'],
    techStack: ['Swift', 'SwiftUI', 'SwiftData', 'WidgetKit', 'Xcode'],
    status: 'not-started',
    isPortfolioWorthy: true,
    phase: 2,
  },
  {
    id: 'proj-ios-capstone',
    title: 'Live Audio & Social App (App Store Ready)',
    description: 'Full native iOS app with Live Activities, audio streaming, and TestFlight release.',
    longDescription: 'Feature-complete iOS app featuring real-time audio rooms, Dynamic Island ActivityKit notifications, Combine reactive streams, and App Store submission readiness.',
    emoji: '🎙️',
    difficulty: 'capstone',
    estimatedTime: '5 weeks',
    skillIds: ['swift', 'swiftui', 'xcode', 'git'],
    careerIds: ['ios-developer'],
    tags: ['ios', 'swiftui', 'capstone', 'appstore'],
    objectives: ['Implement ActivityKit Live Activities', 'Stream audio with AVFoundation', 'Profile memory with Instruments', 'Publish build to Apple TestFlight'],
    techStack: ['Swift', 'SwiftUI', 'Combine', 'ActivityKit', 'AVFoundation'],
    status: 'not-started',
    isPortfolioWorthy: true,
    phase: 4,
  },

  // Flutter Developer
  {
    id: 'proj-flutter-delivery',
    title: 'Cross-Platform Delivery App',
    description: 'Food delivery mobile app running seamlessly on iOS and Android with Riverpod state.',
    longDescription: 'Cross-platform mobile app featuring real-time order tracking, custom interactive cart, Riverpod state management, and Firebase backend synchronization.',
    emoji: '🍔',
    difficulty: 'intermediate',
    estimatedTime: '3 weeks',
    skillIds: ['dart', 'flutter', 'firebase-basics'],
    careerIds: ['flutter-developer'],
    tags: ['flutter', 'dart', 'riverpod', 'mobile'],
    objectives: ['Build shared widget library', 'Manage state with Riverpod', 'Integrate Google Maps for Flutter', 'Connect Firebase Cloud Firestore'],
    techStack: ['Dart', 'Flutter', 'Riverpod', 'Firebase', 'Dio'],
    status: 'not-started',
    isPortfolioWorthy: true,
    phase: 2,
  },
  {
    id: 'proj-flutter-capstone',
    title: 'Full Multi-Platform SaaS Client',
    description: 'E-commerce & SaaS client running simultaneously on iOS, Android, and Web.',
    longDescription: 'Enterprise-grade Flutter application deployed across iOS, Android, and Web browsers. Implements clean architecture, BLoC pattern, native platform channels, and Fastlane CI/CD.',
    emoji: '🎯',
    difficulty: 'capstone',
    estimatedTime: '5 weeks',
    skillIds: ['dart', 'flutter', 'git'],
    careerIds: ['flutter-developer'],
    tags: ['flutter', 'capstone', 'multiplatform', 'bloc'],
    objectives: ['Deploy clean architecture with BLoC', 'Bridge native code via Platform Channels', 'Automate builds with Fastlane CI/CD', 'Deploy to Web and App Stores'],
    techStack: ['Flutter', 'Dart', 'BLoC', 'Fastlane', 'GitHub Actions'],
    status: 'not-started',
    isPortfolioWorthy: true,
    phase: 4,
  },

  // React Native Developer
  {
    id: 'proj-rn-fitness',
    title: 'Offline Fitness Tracker App',
    description: 'React Native workout companion with Expo Router and WatermelonDB offline storage.',
    longDescription: 'Build an offline-first workout logging app using Expo Router, 60fps gesture animations with Reanimated 3, and high-speed local SQLite persistence.',
    emoji: '💪',
    difficulty: 'intermediate',
    estimatedTime: '3 weeks',
    skillIds: ['react-native', 'typescript', 'javascript'],
    careerIds: ['react-native-developer'],
    tags: ['react-native', 'expo', 'reanimated', 'mobile'],
    objectives: ['Implement file-based routing with Expo Router', 'Create fluid gestures with Reanimated 3', 'Local SQLite / MMKV storage', 'Native haptic feedback integration'],
    techStack: ['React Native', 'Expo', 'TypeScript', 'Reanimated', 'Zustand'],
    status: 'not-started',
    isPortfolioWorthy: true,
    phase: 2,
  },
  {
    id: 'proj-rn-capstone',
    title: 'On-Demand Service Marketplace',
    description: 'Cross-platform marketplace with real-time driver tracking, payments, and push alerts.',
    longDescription: 'Complete Uber/Airbnb style on-demand mobile app with push notifications, geolocation maps, live booking updates, and EAS over-the-air deployment pipeline.',
    emoji: '🚕',
    difficulty: 'capstone',
    estimatedTime: '5 weeks',
    skillIds: ['react-native', 'typescript', 'react', 'git'],
    careerIds: ['react-native-developer'],
    tags: ['react-native', 'capstone', 'expo', 'eas'],
    objectives: ['Configure background geolocation', 'Integrate push notifications via Expo EAS', 'Write automated tests with RNTL', 'Publish release builds with EAS Submit'],
    techStack: ['React Native', 'Expo EAS', 'TypeScript', 'Node.js', 'Stripe'],
    status: 'not-started',
    isPortfolioWorthy: true,
    phase: 4,
  },

  // Machine Learning Engineer
  {
    id: 'proj-ml-classifier',
    title: 'Computer Vision Defect Detection API',
    description: 'ResNet / YOLO deep learning model trained with PyTorch and served via FastAPI.',
    longDescription: 'End-to-end image classification and object detection pipeline. Train custom PyTorch models, optimize weights with ONNX Runtime, and containerize an asynchronous FastAPI inference service.',
    emoji: '🔬',
    difficulty: 'intermediate',
    estimatedTime: '3 weeks',
    skillIds: ['python', 'pytorch', 'tensorflow'],
    careerIds: ['ml-engineer'],
    tags: ['ml', 'pytorch', 'fastapi', 'computer-vision'],
    objectives: ['Train PyTorch CNN model with transfer learning', 'Benchmark inference latency with ONNX', 'Containerize FastAPI microservice', 'Write Docker compose deployment'],
    techStack: ['Python', 'PyTorch', 'FastAPI', 'ONNX Runtime', 'Docker'],
    status: 'not-started',
    isPortfolioWorthy: true,
    phase: 2,
  },
  {
    id: 'proj-ml-capstone',
    title: 'Production MLOps Pipeline & Serving System',
    description: 'Automated ML training pipeline with DVC, MLflow tracking, and Ray distributed serving.',
    longDescription: 'Enterprise MLOps deployment pipeline featuring automated data versioning with DVC, experiment tracking with MLflow, continuous retraining with GitHub Actions, and Triton server scaling.',
    emoji: '🧠',
    difficulty: 'capstone',
    estimatedTime: '5 weeks',
    skillIds: ['python', 'pytorch', 'docker', 'statistics'],
    careerIds: ['ml-engineer'],
    tags: ['mlops', 'capstone', 'mlflow', 'kubernetes'],
    objectives: ['Implement DVC data versioning', 'Deploy MLflow tracking server', 'Set up automated model validation CI/CD', 'Monitor production drift with Evidently AI'],
    techStack: ['Python', 'PyTorch', 'MLflow', 'DVC', 'Docker', 'Kubernetes'],
    status: 'not-started',
    isPortfolioWorthy: true,
    phase: 4,
  },

  // Data Scientist
  {
    id: 'proj-ds-churn',
    title: 'Customer Churn & LTV Predictive Model',
    description: 'Statistical classification and survival analysis model to predict customer retention.',
    longDescription: 'Perform thorough exploratory data analysis on a 500k-record telecom dataset. Engineer behavioral features, train XGBoost classifiers with cross-validation, and explain predictions using SHAP values.',
    emoji: '📉',
    difficulty: 'intermediate',
    estimatedTime: '3 weeks',
    skillIds: ['python', 'pandas', 'statistics', 'sql'],
    careerIds: ['data-scientist'],
    tags: ['data-science', 'xgboost', 'shap', 'pandas'],
    objectives: ['Conduct EDA and hypothesis testing', 'Build XGBoost classification model', 'Calculate SHAP feature importance', 'Quantify revenue retention impact'],
    techStack: ['Python', 'Pandas', 'Scikit-learn', 'XGBoost', 'SHAP'],
    status: 'not-started',
    isPortfolioWorthy: true,
    phase: 2,
  },
  {
    id: 'proj-ds-capstone',
    title: 'End-to-End Demand Forecasting Platform',
    description: 'Multi-store sales forecasting system with time-series modeling and interactive Tableau dashboard.',
    longDescription: 'Real-world retail forecasting project combining Prophet/ARIMA time-series models, automated SQL feature generation in BigQuery, and an interactive executive Tableau dashboard.',
    emoji: '📊',
    difficulty: 'capstone',
    estimatedTime: '5 weeks',
    skillIds: ['python', 'statistics', 'sql', 'visualization'],
    careerIds: ['data-scientist'],
    tags: ['data-science', 'capstone', 'forecasting', 'tableau'],
    objectives: ['Build multi-horizon time series models', 'Design automated feature stores in SQL', 'Create interactive Tableau dashboard', 'Present executive business case study'],
    techStack: ['Python', 'Prophet', 'BigQuery', 'Tableau', 'Streamlit'],
    status: 'not-started',
    isPortfolioWorthy: true,
    phase: 4,
  },

  // Ethical Hacker / Cybersecurity
  {
    id: 'proj-eh-scanner',
    title: 'Automated Network & Web Vulnerability Scanner',
    description: 'Python security scanner for port audits, SSL misconfigurations, and CVE detection.',
    longDescription: 'Build a modular penetration testing tool in Python. Features asynchronous port scanning with Nmap integration, automated banner grabbing, directory brute-forcing, and CVE vulnerability lookups.',
    emoji: '🔍',
    difficulty: 'intermediate',
    estimatedTime: '3 weeks',
    skillIds: ['python', 'networking', 'linux'],
    careerIds: ['ethical-hacker', 'security-analyst'],
    tags: ['cybersecurity', 'python', 'pentest', 'networking'],
    objectives: ['Implement async socket scanner', 'Automate Nmap script engine scans', 'Check OWASP Top 10 web vulnerabilities', 'Generate HTML audit report'],
    techStack: ['Python', 'Nmap', 'Socket', 'BeautifulSoup', 'Linux'],
    status: 'not-started',
    isPortfolioWorthy: true,
    phase: 2,
  },
  {
    id: 'proj-eh-capstone',
    title: 'Active Directory Pentest & Enterprise Engagement',
    description: 'Full simulated penetration testing engagement on a multi-domain enterprise Active Directory network.',
    longDescription: 'Execute a simulated corporate red team engagement. Covers initial access, Kerberoasting, AS-REP roasting, lateral movement, domain admin takeover, and professional client remediation report.',
    emoji: '💀',
    difficulty: 'capstone',
    estimatedTime: '5 weeks',
    skillIds: ['networking', 'linux', 'python', 'web-security', 'oscp'],
    careerIds: ['ethical-hacker'],
    tags: ['cybersecurity', 'capstone', 'pentest', 'active-directory'],
    objectives: ['Execute Active Directory privilege escalation', 'Crack Kerberos tickets with Hashcat', 'Perform pass-the-hash lateral movement', 'Write professional executive pentest report'],
    techStack: ['Kali Linux', 'BloodHound', 'Impacket', 'Metasploit', 'Burp Suite'],
    status: 'not-started',
    isPortfolioWorthy: true,
    phase: 4,
  },

  // Generative AI Engineer
  {
    id: 'proj-genai-capstone',
    title: 'Enterprise Multi-Tenant RAG Knowledge Base',
    description: 'Production LLM application with hybrid vector search, LangChain agents, and guardrails.',
    longDescription: 'Architect a secure, multi-tenant enterprise document search system using Pinecone hybrid search (dense + sparse BM25), Cohere reranking, streaming token responses, and NeMo guardrails.',
    emoji: '✨',
    difficulty: 'capstone',
    estimatedTime: '5 weeks',
    skillIds: ['python', 'pytorch', 'docker'],
    careerIds: ['genai-engineer', 'ai-researcher'],
    tags: ['genai', 'rag', 'llm', 'capstone'],
    objectives: ['Build semantic chunking and embedding pipeline', 'Implement hybrid search with Pinecone and Cohere Rerank', 'Add hallucination evaluation with RAGAS', 'Deploy containerized FastAPI with streaming tokens'],
    techStack: ['Python', 'LangChain', 'Pinecone', 'FastAPI', 'Docker', 'vLLM'],
    status: 'not-started',
    isPortfolioWorthy: true,
    phase: 4,
  },

  // Data Engineer
  {
    id: 'proj-de-capstone',
    title: 'Real-Time Lakehouse Event Pipeline',
    description: 'High-volume data highway with Kafka, Spark Streaming, Delta Lake, and dbt.',
    longDescription: 'Build an enterprise streaming pipeline processing 100,000 events/sec. Features Kafka topic ingestion, PySpark Structured Streaming into Delta Lake tables, and automated dbt modeling in Snowflake.',
    emoji: '🗄️',
    difficulty: 'capstone',
    estimatedTime: '5 weeks',
    skillIds: ['python', 'sql', 'docker'],
    careerIds: ['data-engineer'],
    tags: ['data-engineering', 'spark', 'kafka', 'capstone'],
    objectives: ['Deploy distributed Kafka cluster with Docker', 'Write PySpark streaming ingestion job', 'Implement Delta Lake ACID transactions', 'Automate data quality testing with dbt'],
    techStack: ['Python', 'PySpark', 'Apache Kafka', 'Delta Lake', 'dbt', 'Snowflake'],
    status: 'not-started',
    isPortfolioWorthy: true,
    phase: 4,
  },

  // Cloud Engineer
  {
    id: 'proj-cloud-capstone',
    title: 'Multi-Region Enterprise AWS Infrastructure',
    description: 'High-availability infrastructure automated via Terraform with automated disaster recovery.',
    longDescription: 'Design and deploy a complete fault-tolerant AWS multi-tier architecture using Terraform. Features cross-region VPC peering, auto-scaling ECS Fargate clusters, Aurora multi-AZ databases, and Route 53 health failovers.',
    emoji: '☁️',
    difficulty: 'capstone',
    estimatedTime: '5 weeks',
    skillIds: ['docker', 'networking', 'linux'],
    careerIds: ['cloud-engineer'],
    tags: ['cloud', 'aws', 'terraform', 'capstone'],
    objectives: ['Write modular Terraform IaC modules', 'Deploy multi-AZ VPC with private subnets', 'Configure ECS Fargate container auto-scaling', 'Conduct Route 53 disaster recovery failover drill'],
    techStack: ['AWS', 'Terraform', 'Docker', 'ECS Fargate', 'RDS Aurora'],
    status: 'not-started',
    isPortfolioWorthy: true,
    phase: 4,
  },

  // DevOps Engineer
  {
    id: 'proj-devops-capstone',
    title: 'Automated GitOps Kubernetes Delivery Platform',
    description: 'Production CI/CD system with GitHub Actions, Helm charts, ArgoCD, and Prometheus monitoring.',
    longDescription: 'End-to-end automated software delivery pipeline. Developers commit code; GitHub Actions automatically builds and signs container images; ArgoCD synchronizes Helm charts to a Kubernetes cluster with zero downtime.',
    emoji: '🚀',
    difficulty: 'capstone',
    estimatedTime: '5 weeks',
    skillIds: ['docker', 'linux', 'git'],
    careerIds: ['devops-engineer'],
    tags: ['devops', 'kubernetes', 'argocd', 'capstone'],
    objectives: ['Build automated GitHub Actions release matrix', 'Package applications with Helm charts', 'Set up ArgoCD declarative GitOps synchronization', 'Build Grafana cluster health dashboards'],
    techStack: ['Kubernetes', 'Docker', 'ArgoCD', 'Helm', 'GitHub Actions', 'Prometheus'],
    status: 'not-started',
    isPortfolioWorthy: true,
    phase: 4,
  },

  // Database Administrator
  {
    id: 'proj-dba-capstone',
    title: 'High-Availability Clustered Database Cluster',
    description: 'Geo-replicated PostgreSQL cluster with Patroni, Raft consensus, and automated failover.',
    longDescription: 'Design, configure, and stress-test a production-grade PostgreSQL HA cluster using Patroni and Raft for automated leader election, PgBouncer connection pooling, and continuous WAL archive backups.',
    emoji: '💾',
    difficulty: 'capstone',
    estimatedTime: '4 weeks',
    skillIds: ['sql', 'linux'],
    careerIds: ['database-administrator'],
    tags: ['database', 'postgresql', 'dba', 'capstone'],
    objectives: ['Deploy 3-node Patroni PostgreSQL cluster', 'Configure PgBouncer transaction pooling', 'Conduct simulated master node kill failover drill', 'Validate Point-in-Time Recovery with pgBackRest'],
    techStack: ['PostgreSQL', 'Patroni', 'PgBouncer', 'pgBackRest', 'Linux'],
    status: 'not-started',
    isPortfolioWorthy: true,
    phase: 4,
  },

  // Blockchain Developer
  {
    id: 'proj-bc-capstone',
    title: 'Audited Decentralized Token Exchange (DEX)',
    description: 'Solidity AMM smart contracts with Foundry property fuzz testing and Web3 frontend.',
    longDescription: 'Build a Uniswap-style Automated Market Maker DEX. Write gas-optimized Solidity smart contracts with reentrancy protection, test invariants with Foundry Forge fuzzing, and build a Web3 frontend with Viem and Wagmi.',
    emoji: '⛓️',
    difficulty: 'capstone',
    estimatedTime: '5 weeks',
    skillIds: ['javascript', 'typescript', 'react'],
    careerIds: ['blockchain-developer'],
    tags: ['blockchain', 'solidity', 'web3', 'capstone'],
    objectives: ['Implement AMM constant product liquidity pool', 'Write Foundry fuzz tests and invariant checks', 'Audit contracts with Slither static analyzer', 'Connect frontend with Wagmi and MetaMask'],
    techStack: ['Solidity', 'Foundry', 'TypeScript', 'Wagmi', 'Ethers.js'],
    status: 'not-started',
    isPortfolioWorthy: true,
    phase: 4,
  },

  // Embedded Systems Engineer
  {
    id: 'proj-emb-capstone',
    title: 'Connected Smart Telemetry Edge Device',
    description: 'FreeRTOS firmware running on STM32 / ESP32 with sensor reading and MQTT cloud sync.',
    longDescription: 'Program a commercial-grade IoT sensor hub. Features multi-task FreeRTOS scheduling, DMA sensor transfers, deep-sleep battery management, and TLS-encrypted MQTT transmission to AWS IoT Core.',
    emoji: '📡',
    difficulty: 'capstone',
    estimatedTime: '5 weeks',
    skillIds: ['linux'],
    careerIds: ['embedded-engineer'],
    tags: ['embedded', 'iot', 'freertos', 'capstone'],
    objectives: ['Write FreeRTOS multi-threaded firmware in C', 'Configure DMA transfers for I2C/SPI sensors', 'Implement ultra-low-power sleep cycles', 'Transmit TLS encrypted telemetry over MQTT'],
    techStack: ['Embedded C', 'FreeRTOS', 'STM32 / ESP32', 'MQTT', 'AWS IoT Core'],
    status: 'not-started',
    isPortfolioWorthy: true,
    phase: 4,
  },

  // Network Engineer
  {
    id: 'proj-net-capstone',
    title: 'Enterprise Multi-Site Network Infrastructure',
    description: 'Complete corporate network simulated in GNS3 with BGP, OSPF, IPsec VPNs, and Python automation.',
    longDescription: 'Design, simulate, and configure a multi-branch corporate network. Implements redundant core routing with OSPF and BGP, IPsec site-to-site tunnels, Next-Gen firewall policies, and Python automated config auditing.',
    emoji: '🌐',
    difficulty: 'capstone',
    estimatedTime: '4 weeks',
    skillIds: ['networking', 'python', 'linux'],
    careerIds: ['network-engineer'],
    tags: ['networking', 'cisco', 'bgp', 'capstone'],
    objectives: ['Configure multi-area OSPF and eBGP peering', 'Set up redundant IPsec VPN tunnels', 'Implement ACLs and NAT policies on firewalls', 'Automate switch compliance checks with Python'],
    techStack: ['Cisco IOS', 'BGP', 'OSPF', 'Wireshark', 'Python (Netmiko)'],
    status: 'not-started',
    isPortfolioWorthy: true,
    phase: 4,
  },

  // QA Automation Engineer
  {
    id: 'proj-qa-capstone',
    title: 'Enterprise Test Automation Framework',
    description: 'Multi-browser Playwright test framework with POM, parallel test sharding, and Allure reports.',
    longDescription: 'Architect a robust QA test automation framework in TypeScript. Features Page Object Model patterns, parallel test sharding across GitHub Actions runners, automated accessibility scans, and rich Allure HTML reports.',
    emoji: '🔍',
    difficulty: 'capstone',
    estimatedTime: '4 weeks',
    skillIds: ['typescript', 'javascript', 'git'],
    careerIds: ['qa-automation-engineer'],
    tags: ['qa', 'playwright', 'testing', 'capstone'],
    objectives: ['Build scalable Page Object Model architecture', 'Integrate parallel test sharding in CI/CD', 'Automate visual regression diffing', 'Generate Allure test execution dashboard'],
    techStack: ['Playwright', 'TypeScript', 'Allure Report', 'k6', 'GitHub Actions'],
    status: 'not-started',
    isPortfolioWorthy: true,
    phase: 4,
  },

  // Business & Data Analyst
  {
    id: 'proj-ba-capstone',
    title: 'Executive Revenue & Retention BI Dashboard',
    description: 'Interactive PowerBI & Tableau suite analyzing commercial revenue cohorts and customer retention.',
    longDescription: 'Transform a messy 1,000,000-row transactional database into an interactive executive BI dashboard. Features advanced DAX measures, cohort retention analysis, forecasting models, and executive slide deck summaries.',
    emoji: '📈',
    difficulty: 'capstone',
    estimatedTime: '4 weeks',
    skillIds: ['sql', 'visualization', 'python'],
    careerIds: ['business-analyst'],
    tags: ['bi', 'powerbi', 'sql', 'capstone'],
    objectives: ['Build Star schema data model in PowerBI', 'Write complex DAX time-intelligence calculations', 'Analyze customer cohort retention drops', 'Prepare C-suite executive insights presentation'],
    techStack: ['PowerBI', 'Tableau', 'SQL', 'Excel', 'Python'],
    status: 'not-started',
    isPortfolioWorthy: true,
    phase: 4,
  },

  // Security Analyst
  {
    id: 'proj-soc-capstone',
    title: 'Enterprise Incident Response Simulation',
    description: 'Full blue-team incident investigation: SIEM alert triage, memory forensics, and containment.',
    longDescription: 'Conduct a complete SOC defensive investigation on a simulated corporate ransomware attack. Triage Splunk alerts, analyze memory dumps with Volatility, extract IoCs, and produce an executive post-mortem report.',
    emoji: '🛡️',
    difficulty: 'capstone',
    estimatedTime: '4 weeks',
    skillIds: ['networking', 'linux', 'web-security'],
    careerIds: ['security-analyst'],
    tags: ['soc', 'splunk', 'incident-response', 'capstone'],
    objectives: ['Write SPL queries to detect adversary lateral movement', 'Analyze malicious memory injections with Volatility', 'Map attacker TTPs to MITRE ATT&CK', 'Draft official security incident response report'],
    techStack: ['Splunk', 'Microsoft Sentinel', 'Wireshark', 'Volatility', 'Linux'],
    status: 'not-started',
    isPortfolioWorthy: true,
    phase: 4,
  },

  // Product Designer
  {
    id: 'proj-pd-capstone',
    title: 'Comprehensive SaaS Product Redesign & Design System',
    description: 'End-to-end user research, wireframing, Figma design system, and high-fidelity prototype.',
    longDescription: 'Lead a comprehensive product redesign case study. Conduct user interviews, establish a token-based Figma design system with variables, build high-fidelity interactive prototypes, and validate with usability testing.',
    emoji: '📐',
    difficulty: 'capstone',
    estimatedTime: '5 weeks',
    skillIds: ['figma', 'ux-research', 'prototyping', 'design-systems'],
    careerIds: ['product-designer'],
    tags: ['ui-ux', 'figma', 'design-systems', 'capstone'],
    objectives: ['Conduct user research & empathy mapping', 'Build scalable Figma token design system', 'Create interactive micro-interaction prototypes', 'Publish Framer case study portfolio presentation'],
    techStack: ['Figma', 'FigJam', 'Framer', 'UsabilityHub', 'Miro'],
    status: 'not-started',
    isPortfolioWorthy: true,
    phase: 4,
  },

  // Unity Developer
  {
    id: 'proj-unity-capstone',
    title: '3D Action Adventure Game (Steam Ready)',
    description: 'Complete 3D action game with physics combat, custom shaders, audio, and Steam release prep.',
    longDescription: 'Design, program, and polish a complete 3D game in Unity. Implements C# state machines, custom VFX Shader Graph shaders, spatial audio mixing, enemy AI pathfinding, and Steam build deployment.',
    emoji: '🎲',
    difficulty: 'capstone',
    estimatedTime: '5 weeks',
    skillIds: ['csharp', 'unity', 'game-math', 'git'],
    careerIds: ['unity-developer'],
    tags: ['game-dev', 'unity', 'csharp', 'capstone'],
    objectives: ['Program player physics controller in C#', 'Create visual particle effects with Shader Graph', 'Implement enemy NavMesh AI state machine', 'Optimize draw calls and package Steam release'],
    techStack: ['Unity Engine', 'C#', 'Shader Graph', 'Universal Render Pipeline', 'Git'],
    status: 'not-started',
    isPortfolioWorthy: true,
    phase: 4,
  },
];
