export interface RawResource {
  id: string;
  title: string;
  description: string;
  type: 'course' | 'book' | 'video' | 'article' | 'documentation' | 'practice' | 'community';
  level: 'beginner' | 'intermediate' | 'advanced';
  url: string;
  provider: string;
  duration: string;
  isFree: boolean;
  price?: string;
  rating: number;
  skillIds: string[];
  careerIds: string[];
  tags: string[];
  emoji: string;
}

export const rawResources: RawResource[] = [
  // Full Stack Developer
  {
    id: 'res-fs-the-odin-project',
    title: 'The Odin Project: Full Stack JavaScript',
    description: 'Premier free curriculum covering full-stack web development from zero to production.',
    type: 'course',
    level: 'beginner',
    url: 'https://www.theodinproject.com/',
    provider: 'The Odin Project',
    duration: '200 hours',
    isFree: true,
    rating: 4.9,
    skillIds: ['javascript', 'react', 'nodejs', 'sql', 'html-css'],
    careerIds: ['fullstack-developer', 'frontend-developer'],
    tags: ['fullstack', 'react', 'nodejs', 'javascript'],
    emoji: '🔗',
  },
  {
    id: 'res-fs-fullstackopen',
    title: 'Full Stack Open (University of Helsinki)',
    description: 'Deep dive into modern web development with React, Redux, Node.js, MongoDB, GraphQL, and TypeScript.',
    type: 'course',
    level: 'intermediate',
    url: 'https://fullstackopen.com/en/',
    provider: 'University of Helsinki',
    duration: '150 hours',
    isFree: true,
    rating: 5.0,
    skillIds: ['react', 'nodejs', 'typescript', 'docker'],
    careerIds: ['fullstack-developer'],
    tags: ['react', 'nodejs', 'graphql', 'typescript'],
    emoji: '🎓',
  },

  // Frontend Developer
  {
    id: 'res-fe-react-docs',
    title: 'React Official Documentation (react.dev)',
    description: 'Official interactive documentation for modern React with Hooks, Server Components, and interactive sandboxes.',
    type: 'documentation',
    level: 'beginner',
    url: 'https://react.dev/',
    provider: 'Meta',
    duration: '30 hours',
    isFree: true,
    rating: 4.9,
    skillIds: ['react', 'javascript'],
    careerIds: ['frontend-developer', 'fullstack-developer'],
    tags: ['react', 'official', 'frontend'],
    emoji: '⚛️',
  },
  {
    id: 'res-fe-total-typescript',
    title: 'Total TypeScript Core Essentials',
    description: 'Master TypeScript types, generics, and discriminated unions for modern React web applications.',
    type: 'course',
    level: 'intermediate',
    url: 'https://www.totaltypescript.com/',
    provider: 'Matt Pocock',
    duration: '25 hours',
    isFree: true,
    rating: 4.9,
    skillIds: ['typescript'],
    careerIds: ['frontend-developer', 'fullstack-developer'],
    tags: ['typescript', 'frontend'],
    emoji: '🔷',
  },

  // Backend Engineer
  {
    id: 'res-be-system-design-primer',
    title: 'The System Design Primer',
    description: 'Learn how to design large-scale distributed systems, caching tiers, load balancers, and database sharding.',
    type: 'article',
    level: 'advanced',
    url: 'https://github.com/donnemartin/system-design-primer',
    provider: 'Donne Martin',
    duration: '40 hours',
    isFree: true,
    rating: 5.0,
    skillIds: ['nodejs', 'sql', 'docker'],
    careerIds: ['backend-engineer', 'fullstack-developer'],
    tags: ['system-design', 'distributed-systems', 'architecture'],
    emoji: '⚡',
  },
  {
    id: 'res-be-nodejs-design-patterns',
    title: 'Node.js Design Patterns Guide',
    description: 'Master asynchronous control flow, streams, microservices, and design patterns in enterprise Node.js.',
    type: 'book',
    level: 'intermediate',
    url: 'https://www.nodejsdesignpatterns.com/',
    provider: 'Mario Casciaro',
    duration: '35 hours',
    isFree: false,
    price: '$39.99',
    rating: 4.8,
    skillIds: ['nodejs'],
    careerIds: ['backend-engineer'],
    tags: ['nodejs', 'patterns', 'backend'],
    emoji: '📗',
  },

  // Android Developer
  {
    id: 'res-android-compose-course',
    title: 'Android Basics with Jetpack Compose',
    description: 'Official Google curriculum for building native Android applications with Kotlin and Jetpack Compose.',
    type: 'course',
    level: 'beginner',
    url: 'https://developer.android.com/courses/android-basics-compose/course',
    provider: 'Google',
    duration: '80 hours',
    isFree: true,
    rating: 4.9,
    skillIds: ['kotlin', 'jetpack-compose', 'android-sdk'],
    careerIds: ['android-developer'],
    tags: ['android', 'kotlin', 'compose', 'official'],
    emoji: '🤖',
  },
  {
    id: 'res-android-kotlin-koans',
    title: 'Kotlin Koans Interactive Practice',
    description: 'Solve interactive coding challenges to master idiomatic Kotlin syntax and standard library features.',
    type: 'practice',
    level: 'beginner',
    url: 'https://play.kotlinlang.org/koans/overview',
    provider: 'JetBrains',
    duration: '12 hours',
    isFree: true,
    rating: 4.8,
    skillIds: ['kotlin'],
    careerIds: ['android-developer'],
    tags: ['kotlin', 'practice', 'android'],
    emoji: '🎯',
  },

  // iOS Developer
  {
    id: 'res-ios-100-days-swiftui',
    title: '100 Days of SwiftUI',
    description: 'Free collection of videos, tutorials, and practical iOS projects by Paul Hudson.',
    type: 'course',
    level: 'beginner',
    url: 'https://www.hackingwithswift.com/100/swiftui',
    provider: 'Hacking with Swift',
    duration: '100 hours',
    isFree: true,
    rating: 5.0,
    skillIds: ['swift', 'swiftui', 'xcode'],
    careerIds: ['ios-developer'],
    tags: ['ios', 'swift', 'swiftui'],
    emoji: '🍎',
  },

  // Flutter Developer
  {
    id: 'res-flutter-official-codelabs',
    title: 'Flutter Official Codelabs & Documentation',
    description: 'Step-by-step Google guides building multi-platform apps with Dart and Flutter.',
    type: 'course',
    level: 'beginner',
    url: 'https://docs.flutter.dev/codelabs',
    provider: 'Google',
    duration: '40 hours',
    isFree: true,
    rating: 4.8,
    skillIds: ['dart', 'flutter'],
    careerIds: ['flutter-developer'],
    tags: ['flutter', 'dart', 'mobile'],
    emoji: '🎯',
  },

  // React Native Developer
  {
    id: 'res-rn-expo-docs',
    title: 'Expo & React Native Documentation',
    description: 'Learn universal native apps with Expo Router, TypeScript, and file-based navigation.',
    type: 'documentation',
    level: 'beginner',
    url: 'https://docs.expo.dev/',
    provider: 'Expo',
    duration: '25 hours',
    isFree: true,
    rating: 4.9,
    skillIds: ['react-native', 'typescript', 'react'],
    careerIds: ['react-native-developer'],
    tags: ['react-native', 'expo', 'mobile'],
    emoji: '📱',
  },

  // Machine Learning Engineer
  {
    id: 'res-ml-fastai-course',
    title: 'Practical Deep Learning for Coders',
    description: 'Top-tier deep learning course teaching PyTorch, computer vision, NLP, and model deployment.',
    type: 'course',
    level: 'intermediate',
    url: 'https://course.fast.ai/',
    provider: 'fast.ai',
    duration: '70 hours',
    isFree: true,
    rating: 4.9,
    skillIds: ['python', 'pytorch'],
    careerIds: ['ml-engineer', 'ai-researcher'],
    tags: ['deep-learning', 'pytorch', 'ai'],
    emoji: '🧠',
  },

  // Data Scientist
  {
    id: 'res-ds-statquest',
    title: 'StatQuest: Machine Learning & Statistics',
    description: 'Clear visual breakdowns of machine learning algorithms, PCA, logistic regression, and neural nets.',
    type: 'video',
    level: 'beginner',
    url: 'https://statquest.org/',
    provider: 'Josh Starmer',
    duration: '30 hours',
    isFree: true,
    rating: 5.0,
    skillIds: ['statistics', 'python'],
    careerIds: ['data-scientist', 'ml-engineer', 'business-analyst'],
    tags: ['statistics', 'machine-learning', 'math'],
    emoji: '📊',
  },

  // Ethical Hacker / Cybersecurity
  {
    id: 'res-eh-portswigger-academy',
    title: 'PortSwigger Web Security Academy',
    description: 'Free, interactive web security training and labs from the creators of Burp Suite.',
    type: 'practice',
    level: 'intermediate',
    url: 'https://portswigger.net/web-security',
    provider: 'PortSwigger',
    duration: '80 hours',
    isFree: true,
    rating: 5.0,
    skillIds: ['web-security', 'networking'],
    careerIds: ['ethical-hacker', 'security-analyst'],
    tags: ['security', 'burp-suite', 'owasp', 'pentest'],
    emoji: '💀',
  },

  // Generative AI Engineer
  {
    id: 'res-genai-deeplearning-ai',
    title: 'Building Applications with LLMs & RAG',
    description: 'Short courses on LangChain, vector search, fine-tuning, and multi-agent AI systems.',
    type: 'course',
    level: 'intermediate',
    url: 'https://www.deeplearning.ai/short-courses/',
    provider: 'DeepLearning.AI',
    duration: '20 hours',
    isFree: true,
    rating: 4.9,
    skillIds: ['python', 'pytorch'],
    careerIds: ['genai-engineer', 'ai-researcher'],
    tags: ['genai', 'langchain', 'llm'],
    emoji: '✨',
  },

  // Data Engineer
  {
    id: 'res-de-data-engineering-zoomcamp',
    title: 'Data Engineering Zoomcamp',
    description: 'Free comprehensive bootcamp on Docker, Terraform, GCP/AWS, Spark, Kafka, and dbt.',
    type: 'course',
    level: 'intermediate',
    url: 'https://github.com/DataTalksClub/data-engineering-zoomcamp',
    provider: 'DataTalksClub',
    duration: '90 hours',
    isFree: true,
    rating: 4.9,
    skillIds: ['python', 'sql', 'docker'],
    careerIds: ['data-engineer'],
    tags: ['data-engineering', 'spark', 'kafka', 'dbt'],
    emoji: '🗄️',
  },

  // Cloud Engineer
  {
    id: 'res-cloud-aws-skill-builder',
    title: 'AWS Cloud Solutions Architect Learning Path',
    description: 'Official AWS interactive digital courses on cloud architecture, VPCs, IAM, and high availability.',
    type: 'course',
    level: 'intermediate',
    url: 'https://explore.skillbuilder.aws/',
    provider: 'Amazon Web Services',
    duration: '60 hours',
    isFree: true,
    rating: 4.8,
    skillIds: ['docker', 'networking', 'linux'],
    careerIds: ['cloud-engineer'],
    tags: ['aws', 'cloud', 'architecture'],
    emoji: '☁️',
  },

  // DevOps Engineer
  {
    id: 'res-devops-roadmap-sh',
    title: 'DevOps & SRE Interactive Roadmap & Guide',
    description: 'Community-driven roadmap for DevOps tools: Docker, Kubernetes, CI/CD, and Prometheus.',
    type: 'article',
    level: 'intermediate',
    url: 'https://roadmap.sh/devops',
    provider: 'Roadmap.sh',
    duration: '40 hours',
    isFree: true,
    rating: 4.9,
    skillIds: ['docker', 'linux', 'git'],
    careerIds: ['devops-engineer'],
    tags: ['devops', 'kubernetes', 'ci-cd'],
    emoji: '🚀',
  },

  // Database Administrator
  {
    id: 'res-dba-use-the-index-luke',
    title: 'Use The Index, Luke: SQL Indexing Guide',
    description: 'A guide to database performance for developers and DBAs, covering B-Trees, joins, and indexing.',
    type: 'article',
    level: 'advanced',
    url: 'https://use-the-index-luke.com/',
    provider: 'Markus Winand',
    duration: '20 hours',
    isFree: true,
    rating: 4.9,
    skillIds: ['sql'],
    careerIds: ['database-administrator'],
    tags: ['sql', 'indexing', 'database', 'dba'],
    emoji: '💾',
  },

  // Blockchain Developer
  {
    id: 'res-bc-speedrun-ethereum',
    title: 'SpeedRun Ethereum & Scaffold-ETH',
    description: 'Interactive quest-based challenges building Solidity smart contracts, NFTs, and DeFi apps.',
    type: 'practice',
    level: 'intermediate',
    url: 'https://speedrunethereum.com/',
    provider: 'BuidlGuidl',
    duration: '45 hours',
    isFree: true,
    rating: 4.9,
    skillIds: ['javascript', 'typescript'],
    careerIds: ['blockchain-developer'],
    tags: ['solidity', 'ethereum', 'web3'],
    emoji: '⛓️',
  },

  // Embedded Systems Engineer
  {
    id: 'res-emb-quantum-leaps-c',
    title: 'Modern Embedded Systems Programming',
    description: 'Video course on ARM Cortex-M microcontroller programming, registers, and RTOS concurrency.',
    type: 'video',
    level: 'intermediate',
    url: 'https://www.youtube.com/playlist?list=PLPW8O6W-1chwyTzI3BHwBLbGQoPFxPAPM',
    provider: 'Quantum Leaps',
    duration: '35 hours',
    isFree: true,
    rating: 5.0,
    skillIds: ['linux'],
    careerIds: ['embedded-engineer'],
    tags: ['embedded', 'arm', 'c', 'microcontroller'],
    emoji: '📡',
  },

  // Network Engineer
  {
    id: 'res-net-jeremy-it-lab',
    title: 'Jeremy\'s IT Lab: Free CCNA Course',
    description: 'Complete video course and packet tracer labs preparing for Cisco CCNA certification.',
    type: 'course',
    level: 'beginner',
    url: 'https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivmtM8dwwmcJY58',
    provider: 'Jeremy\'s IT Lab',
    duration: '60 hours',
    isFree: true,
    rating: 5.0,
    skillIds: ['networking', 'linux'],
    careerIds: ['network-engineer'],
    tags: ['cisco', 'ccna', 'networking'],
    emoji: '🌐',
  },

  // QA Automation Engineer
  {
    id: 'res-qa-playwright-docs',
    title: 'Playwright Official Documentation & Guides',
    description: 'Learn modern end-to-end testing, locators, page object models, and test sharding.',
    type: 'documentation',
    level: 'beginner',
    url: 'https://playwright.dev/docs/intro',
    provider: 'Microsoft',
    duration: '20 hours',
    isFree: true,
    rating: 4.9,
    skillIds: ['typescript', 'javascript'],
    careerIds: ['qa-automation-engineer'],
    tags: ['playwright', 'testing', 'qa'],
    emoji: '🔍',
  },

  // Business & Data Analyst
  {
    id: 'res-ba-maven-analytics',
    title: 'Maven Analytics: Power BI & Business Intelligence',
    description: 'Master DAX formulas, Power BI report authoring, and executive dashboard design.',
    type: 'course',
    level: 'beginner',
    url: 'https://www.mavenanalytics.io/',
    provider: 'Maven Analytics',
    duration: '50 hours',
    isFree: false,
    price: '$29/mo',
    rating: 4.9,
    skillIds: ['visualization', 'sql'],
    careerIds: ['business-analyst'],
    tags: ['powerbi', 'analytics', 'bi'],
    emoji: '📈',
  },

  // Security Analyst
  {
    id: 'res-soc-lets-defend',
    title: 'LetsDefend: Blue Team Training & SOC Simulation',
    description: 'Hands-on practice triaging real malware alerts, investigating log telemetry, and incident response.',
    type: 'practice',
    level: 'intermediate',
    url: 'https://letsdefend.io/',
    provider: 'LetsDefend',
    duration: '40 hours',
    isFree: true,
    rating: 4.8,
    skillIds: ['networking', 'linux', 'web-security'],
    careerIds: ['security-analyst'],
    tags: ['soc', 'blue-team', 'siem'],
    emoji: '🛡️',
  },

  // Product Designer
  {
    id: 'res-pd-figma-learn',
    title: 'Figma Community & Design Systems Academy',
    description: 'Learn Auto-Layout, Variables, Component sets, Design Tokens, and responsive prototyping.',
    type: 'course',
    level: 'beginner',
    url: 'https://help.figma.com/hc/en-us/categories/360002042553-Figma-Design',
    provider: 'Figma',
    duration: '30 hours',
    isFree: true,
    rating: 4.9,
    skillIds: ['figma', 'design-systems', 'prototyping'],
    careerIds: ['product-designer'],
    tags: ['figma', 'ui-ux', 'design-systems'],
    emoji: '📐',
  },

  // Unity Developer
  {
    id: 'res-unity-learn',
    title: 'Unity Learn: Junior Programmer Pathway',
    description: 'Official self-paced curriculum teaching C# scripting, physics, audio, and 3D game mechanics.',
    type: 'course',
    level: 'beginner',
    url: 'https://learn.unity.com/pathway/junior-programmer',
    provider: 'Unity Technologies',
    duration: '60 hours',
    isFree: true,
    rating: 4.8,
    skillIds: ['csharp', 'unity', 'game-math'],
    careerIds: ['unity-developer'],
    tags: ['unity', 'csharp', 'gamedev'],
    emoji: '🎲',
  },
];
